/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ospedale.view;

import java.awt.Color;
import java.util.ArrayList;
import com.ospedale.model.Appointment;
import com.ospedale.model.Doctor;
import com.ospedale.model.Hospitalization;
import com.ospedale.model.Patient;
import com.ospedale.model.Specialty;
import com.ospedale.model.User;

/**
 *
 * @author jjlora
 * @author edangulo
 */
public class AdminDashboardView extends javax.swing.JFrame {

    private int x, y;
    private ArrayList<User> users;
    private ArrayList<Appointment>appointments;
    private ArrayList<Hospitalization>hospitalizations;
    private User user;
    public AdminDashboardView(User user, ArrayList<User>users,ArrayList<Hospitalization> hospitalizations, ArrayList<Appointment> appointments) {
        initComponents();
        this.user = user;
        this.users = users;
        this.hospitalizations = hospitalizations;
        this.appointments = appointments;
        this.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GeneralPane = new com.ospedale.view.PanelRound();
        TitleBar = new com.ospedale.view.PanelRound();
        CloseBtn = new javax.swing.JButton();
        TitleLabel = new javax.swing.JLabel();
        AdminPanel = new com.ospedale.view.PanelRound();
        DoctorLaunchBtn = new javax.swing.JButton();
        PatientLaunchBtn = new javax.swing.JButton();
        FirstNameLabel = new javax.swing.JLabel();
        FirstNameTxt = new javax.swing.JTextField();
        LastNameLabel = new javax.swing.JLabel();
        LastNameTxt = new javax.swing.JTextField();
        IDLabel = new javax.swing.JLabel();
        IDTxt = new javax.swing.JTextField();
        SpecialtyLabel = new javax.swing.JLabel();
        LicenseNumberLabel = new javax.swing.JLabel();
        LicenseNumberTxt = new javax.swing.JTextField();
        OfficeLabel = new javax.swing.JLabel();
        OfficeTxt = new javax.swing.JTextField();
        UserNameLabel = new javax.swing.JLabel();
        UserNameTxt = new javax.swing.JTextField();
        PasswdLabel = new javax.swing.JLabel();
        PasswdTxt = new javax.swing.JTextField();
        PasswdConfLabel = new javax.swing.JLabel();
        PasswdConfTxt = new javax.swing.JTextField();
        SpecialtyDropdown = new javax.swing.JComboBox<>();
        DoctorRegistrationBtn = new javax.swing.JButton();
        DoctorPatientImpersonationSeparator = new javax.swing.JSeparator();
        DoctorSelectDropdown = new javax.swing.JComboBox<>();
        DoctorImpersonationLabel = new javax.swing.JLabel();
        PatientImpersonationLabel = new javax.swing.JLabel();
        PatientSelectDropdown = new javax.swing.JComboBox<>();
        DrRegistrationImpersonationSeparator = new javax.swing.JSeparator();
        LogoutBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        GeneralPane.setRadius(50);

        TitleBar.setRadius(50);
        TitleBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                TitleBarMouseDragged(evt);
            }
        });
        TitleBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TitleBarMousePressed(evt);
            }
        });

        CloseBtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        CloseBtn.setText("X");
        CloseBtn.setBorderPainted(false);
        CloseBtn.setContentAreaFilled(false);
        CloseBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CloseBtn.setFocusable(false);
        CloseBtn.setRequestFocusEnabled(false);
        CloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseBtnActionPerformed(evt);
            }
        });

        TitleLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        TitleLabel.setText("ADMIN VIEW");

        javax.swing.GroupLayout TitleBarLayout = new javax.swing.GroupLayout(TitleBar);
        TitleBar.setLayout(TitleBarLayout);
        TitleBarLayout.setHorizontalGroup(
            TitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TitleBarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(TitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CloseBtn)
                .addGap(19, 19, 19))
        );
        TitleBarLayout.setVerticalGroup(
            TitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(CloseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TitleLabel))
        );

        DoctorLaunchBtn.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        DoctorLaunchBtn.setText("DOCTOR VIEW");
        DoctorLaunchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorLaunchBtnActionPerformed(evt);
            }
        });

        PatientLaunchBtn.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        PatientLaunchBtn.setText("PATIENT VIEW");
        PatientLaunchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientLaunchBtnActionPerformed(evt);
            }
        });

        FirstNameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        FirstNameLabel.setText("Firstname");

        FirstNameTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        LastNameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        LastNameLabel.setText("Lastname");

        LastNameTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        IDLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        IDLabel.setText("ID");

        IDTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        SpecialtyLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        SpecialtyLabel.setText("Specialty");

        LicenseNumberLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        LicenseNumberLabel.setText("License Number");

        LicenseNumberTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        OfficeLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        OfficeLabel.setText("Assigned office");

        OfficeTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        UserNameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        UserNameLabel.setText("User");

        UserNameTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        PasswdLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PasswdLabel.setText("Password");

        PasswdTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        PasswdConfLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PasswdConfLabel.setText("Password confirmation");

        PasswdConfTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        SpecialtyDropdown.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        SpecialtyDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "General Medicine", "Cardiology", "Pediatrics", "Neurology", "Traumatology & Orthopedics", "Gynecology & Obstetrics", "Dermatology", "Psychiatry", "Oncology", "Ophthalmology", "Internal Medicine" }));

        DoctorRegistrationBtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        DoctorRegistrationBtn.setText("Save");
        DoctorRegistrationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorRegistrationBtnActionPerformed(evt);
            }
        });

        DoctorPatientImpersonationSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        DoctorSelectDropdown.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        DoctorSelectDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        DoctorImpersonationLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        DoctorImpersonationLabel.setText("Doctor");

        PatientImpersonationLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PatientImpersonationLabel.setText("Patient");

        PatientSelectDropdown.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PatientSelectDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        DrRegistrationImpersonationSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        LogoutBtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        LogoutBtn.setText("Logout");
        LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AdminPanelLayout = new javax.swing.GroupLayout(AdminPanel);
        AdminPanel.setLayout(AdminPanelLayout);
        AdminPanelLayout.setHorizontalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminPanelLayout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(DoctorRegistrationBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(AdminPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AdminPanelLayout.createSequentialGroup()
                                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FirstNameLabel)
                                    .addComponent(SpecialtyLabel))
                                .addGap(18, 18, 18)
                                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(AdminPanelLayout.createSequentialGroup()
                                        .addComponent(SpecialtyDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(LicenseNumberLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(LicenseNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(AdminPanelLayout.createSequentialGroup()
                                        .addComponent(FirstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(LastNameLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(LastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(IDLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(IDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(AdminPanelLayout.createSequentialGroup()
                                .addComponent(OfficeLabel)
                                .addGap(18, 18, 18)
                                .addComponent(OfficeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(AdminPanelLayout.createSequentialGroup()
                                    .addComponent(UserNameLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(UserNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(AdminPanelLayout.createSequentialGroup()
                                    .addComponent(PasswdLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(PasswdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(AdminPanelLayout.createSequentialGroup()
                                    .addComponent(PasswdConfLabel)
                                    .addGap(18, 18, 18)
                                    .addComponent(PasswdConfTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DoctorLaunchBtn)
                            .addGroup(AdminPanelLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(DoctorSelectDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AdminPanelLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(DoctorImpersonationLabel)))
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LogoutBtn)
                        .addGap(318, 318, 318)))
                .addComponent(DoctorPatientImpersonationSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PatientLaunchBtn)
                            .addGroup(AdminPanelLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(PatientSelectDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(AdminPanelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(PatientImpersonationLabel)))
                .addGap(88, 88, 88))
            .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminPanelLayout.createSequentialGroup()
                    .addContainerGap(707, Short.MAX_VALUE)
                    .addComponent(DrRegistrationImpersonationSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(523, 523, 523)))
        );
        AdminPanelLayout.setVerticalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addComponent(DoctorPatientImpersonationSeparator)
                .addContainerGap())
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameLabel)
                    .addComponent(FirstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastNameLabel)
                    .addComponent(LastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDLabel)
                    .addComponent(IDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpecialtyLabel)
                    .addComponent(SpecialtyDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LicenseNumberLabel)
                    .addComponent(LicenseNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OfficeLabel)
                    .addComponent(OfficeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminPanelLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UserNameLabel)
                            .addComponent(UserNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PasswdLabel)
                            .addComponent(PasswdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PasswdConfLabel)
                            .addComponent(PasswdConfTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AdminPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(DoctorImpersonationLabel)
                        .addGap(18, 18, 18)
                        .addComponent(DoctorSelectDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(DoctorLaunchBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(DoctorRegistrationBtn)
                .addGap(123, 123, 123)
                .addComponent(LogoutBtn)
                .addGap(38, 38, 38))
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(PatientImpersonationLabel)
                .addGap(18, 18, 18)
                .addComponent(PatientSelectDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(PatientLaunchBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AdminPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(DrRegistrationImpersonationSeparator)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout GeneralPaneLayout = new javax.swing.GroupLayout(GeneralPane);
        GeneralPane.setLayout(GeneralPaneLayout);
        GeneralPaneLayout.setHorizontalGroup(
            GeneralPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TitleBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        GeneralPaneLayout.setVerticalGroup(
            GeneralPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeneralPaneLayout.createSequentialGroup()
                .addComponent(TitleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GeneralPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GeneralPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TitleBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TitleBarMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_TitleBarMousePressed

    private void TitleBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TitleBarMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_TitleBarMouseDragged

    private void CloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_CloseBtnActionPerformed

    private void DoctorRegistrationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorRegistrationBtnActionPerformed
        String firstname = FirstNameTxt.getText();
        String lastname = LastNameTxt.getText();
        long id = Long.parseLong(IDTxt.getText());
        String spec = SpecialtyDropdown.getItemAt(SpecialtyDropdown.getSelectedIndex());
        String licenseNumber = LicenseNumberTxt.getText();
        String assignedOffice = OfficeTxt.getText();
        String username = UserNameTxt.getText();
        String password = PasswdTxt.getText();
        String comPassword = PasswdConfTxt.getText();
        Specialty specialty = Specialty.valueOf(spec.replaceAll(" &", "").replaceAll(" ", "_"));
        if (password.equals(comPassword)) {
            users.add(new Doctor(id, username, firstname, lastname, password, specialty, licenseNumber, assignedOffice));
        }
    }//GEN-LAST:event_DoctorRegistrationBtnActionPerformed

    private void DoctorLaunchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorLaunchBtnActionPerformed
        long idDoctor = Long.parseLong(DoctorSelectDropdown.getItemAt(DoctorSelectDropdown.getSelectedIndex()));
        Doctor temp = null;
        for(User use:this.users){
            if(use.getId() == idDoctor)
                temp =(Doctor) user;
        }
        DoctorDashboardView doctor = new DoctorDashboardView(user,temp, users, hospitalizations,appointments);
        this.setVisible(false);
        doctor.setVisible(true);
    }//GEN-LAST:event_DoctorLaunchBtnActionPerformed

    private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtnActionPerformed
        
        LoginRegistrationView login = new LoginRegistrationView();
        this.setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_LogoutBtnActionPerformed

    private void PatientLaunchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientLaunchBtnActionPerformed
        long idPatient = Long.parseLong(DoctorSelectDropdown.getItemAt(DoctorSelectDropdown.getSelectedIndex()));
        Patient temp = null;
        for(User use:this.users){
            if(use.getId() == idPatient)
                temp =(Patient) user;
        }
        PatientDashboardView patient = new PatientDashboardView(user,temp,users,appointments,hospitalizations);
        this.setVisible(false);
        patient.setVisible(true);
    }//GEN-LAST:event_PatientLaunchBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.ospedale.view.PanelRound AdminPanel;
    private javax.swing.JButton CloseBtn;
    private javax.swing.JLabel DoctorImpersonationLabel;
    private javax.swing.JButton DoctorLaunchBtn;
    private javax.swing.JSeparator DoctorPatientImpersonationSeparator;
    private javax.swing.JButton DoctorRegistrationBtn;
    private javax.swing.JComboBox<String> DoctorSelectDropdown;
    private javax.swing.JSeparator DrRegistrationImpersonationSeparator;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JTextField FirstNameTxt;
    private com.ospedale.view.PanelRound GeneralPane;
    private javax.swing.JLabel IDLabel;
    private javax.swing.JTextField IDTxt;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JTextField LastNameTxt;
    private javax.swing.JLabel LicenseNumberLabel;
    private javax.swing.JTextField LicenseNumberTxt;
    private javax.swing.JButton LogoutBtn;
    private javax.swing.JLabel OfficeLabel;
    private javax.swing.JTextField OfficeTxt;
    private javax.swing.JLabel PasswdConfLabel;
    private javax.swing.JTextField PasswdConfTxt;
    private javax.swing.JLabel PasswdLabel;
    private javax.swing.JTextField PasswdTxt;
    private javax.swing.JLabel PatientImpersonationLabel;
    private javax.swing.JButton PatientLaunchBtn;
    private javax.swing.JComboBox<String> PatientSelectDropdown;
    private javax.swing.JComboBox<String> SpecialtyDropdown;
    private javax.swing.JLabel SpecialtyLabel;
    private com.ospedale.view.PanelRound TitleBar;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JLabel UserNameLabel;
    private javax.swing.JTextField UserNameTxt;
    // End of variables declaration//GEN-END:variables
}
