/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ospedale.view;

import java.awt.Color;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;
import com.ospedale.model.Administrator;
import com.ospedale.model.Appointment;
import com.ospedale.model.AppointmentStatus;
import com.ospedale.controller.AppointmentController;
import com.ospedale.controller.DoctorController;
import com.ospedale.model.Doctor;
import com.ospedale.model.Hospitalization;
import com.ospedale.controller.HospitalizationController;
import com.ospedale.model.HospitalizationStatus;
import com.ospedale.model.Patient;
import com.ospedale.model.Prescription;
import com.ospedale.model.RoomType;
import com.ospedale.model.Specialty;
import com.ospedale.model.User;
import com.ospedale.model.storage.Storage;
import com.ospedale.controller.utils.Response;
import com.ospedale.controller.utils.Status;
import com.ospedale.controller.NotificationController;
import com.ospedale.controller.PrescriptionController;

/**
 *
 * @author jjlora
 * @author edangulo
 * @author marianaserrato
 * @author orarroyo
 */
public class DoctorDashboardView extends javax.swing.JFrame {

    private int x, y;
    private User user;
    private ArrayList<User> users;
    private ArrayList<Hospitalization>hospitalizations;
    private ArrayList<Appointment>appointments;
    private Doctor doctor;
    private Patient patient;
    public DoctorDashboardView(User user,Doctor doc, ArrayList<User> users,ArrayList<Hospitalization> hospitalizations,ArrayList<Appointment> appointments) {
        initComponents();
        this.user = user;
        this.users = users;
        this.doctor = doc;
        this.hospitalizations = hospitalizations;
        this.appointments = appointments;
        if (user instanceof Administrator)
            BackBtn.setVisible(true);
        else    
            BackBtn.setVisible(false);
        this.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GeneralPane = new com.ospedale.view.PanelRound();
        TitleBar = new com.ospedale.view.PanelRound();
        CloseBtn = new javax.swing.JButton();
        TitleLabel = new javax.swing.JLabel();
        BackBtn = new javax.swing.JButton();
        TabbedPane = new javax.swing.JTabbedPane();
        AppointmentPane = new javax.swing.JPanel();
        FilterTotalAppointmentsBtn = new javax.swing.JRadioButton();
        ScrollableAppointmentsPane = new javax.swing.JScrollPane();
        AppointmentDisplayTable = new javax.swing.JTable();
        FilterPendingAppointmentsBtn = new javax.swing.JRadioButton();
        AppointmentLogoutBtn = new javax.swing.JButton();
        HistoricalAppointmentsPane = new javax.swing.JPanel();
        PatientSelectDropdown = new javax.swing.JComboBox<>();
        PatientLabel = new javax.swing.JLabel();
        ScrollableHistoricalAppointmentsPane = new javax.swing.JScrollPane();
        HistoricalAppointmentsTable = new javax.swing.JTable();
        SearchBtn = new javax.swing.JButton();
        InfoEditingPane = new javax.swing.JPanel();
        FirstNameLabel = new javax.swing.JLabel();
        FirstNameTxt = new javax.swing.JTextField();
        LastNameLabel = new javax.swing.JLabel();
        LastNameTxt = new javax.swing.JTextField();
        SpecialtyLabel = new javax.swing.JLabel();
        LicenseNumberLabel = new javax.swing.JLabel();
        LicenseNumberTxt = new javax.swing.JTextField();
        OfficeLabel = new javax.swing.JLabel();
        UserNameRegistrationTxt = new javax.swing.JTextField();
        UserNameLabel = new javax.swing.JLabel();
        OfficeTxt = new javax.swing.JTextField();
        PasswdTxt = new javax.swing.JTextField();
        PasswdLabel = new javax.swing.JLabel();
        PasswdConfLabel = new javax.swing.JLabel();
        PasswdConfTxt = new javax.swing.JTextField();
        SpecialtyDropdown = new javax.swing.JComboBox<>();
        RegisterBtn = new javax.swing.JButton();
        AppointmentMgmtPane = new javax.swing.JPanel();
        AppointmentIDLabel = new javax.swing.JLabel();
        AcceptAppointmentSectionLabel = new javax.swing.JLabel();
        AcceptAppointmentSelectorDropdown = new javax.swing.JComboBox<>();
        Accept_RescheduleSeparator = new javax.swing.JSeparator();
        AcceptanceAppointmentBtn = new javax.swing.JButton();
        ReschulingAppointmentLabel = new javax.swing.JLabel();
        RescheduleAppointmentSelectorLabel = new javax.swing.JLabel();
        RescheduleAppointmentDropdown = new javax.swing.JComboBox<>();
        AppointmentReschedulingBtn = new javax.swing.JButton();
        NewTImeLabel = new javax.swing.JLabel();
        NewTimeTxt = new javax.swing.JTextField();
        ReasonLabel = new javax.swing.JLabel();
        ReasonTxt = new javax.swing.JTextField();
        Reschedule_CompleteSeparator = new javax.swing.JSeparator();
        CompletingAppointmentLabel = new javax.swing.JLabel();
        CompleteAppointmentSelectorLabel = new javax.swing.JLabel();
        CompleteAppointmentSelectorDropdown = new javax.swing.JComboBox<>();
        DiagnosisLabel = new javax.swing.JLabel();
        AppointmentObservationsLabel = new javax.swing.JLabel();
        RecTreatmentLabel = new javax.swing.JLabel();
        FollowUpLabel = new javax.swing.JLabel();
        CompleteAppointmentBtn = new javax.swing.JButton();
        HospitalizationLabel = new javax.swing.JLabel();
        ReasonHospitalizationLabel = new javax.swing.JLabel();
        HospStartDateLabel = new javax.swing.JLabel();
        HospStartDateTxt = new javax.swing.JTextField();
        HospDurationLabel = new javax.swing.JLabel();
        HospDurationTxt = new javax.swing.JTextField();
        HospObservationsLabel = new javax.swing.JLabel();
        HospObservationsScrlPane = new javax.swing.JScrollPane();
        HospObservationsTxt = new javax.swing.JTextArea();
        GenerateHospBtn = new javax.swing.JButton();
        RequestSelectDropdown = new javax.swing.JComboBox<>();
        RequestSelBtn = new javax.swing.JRadioButton();
        PatientIDSelBtn = new javax.swing.JRadioButton();
        DiagnosisScrlPane = new javax.swing.JScrollPane();
        DiagnosisTxt = new javax.swing.JTextArea();
        AppointmentObservationsScrlPane = new javax.swing.JScrollPane();
        AppointmentObservationsTxt = new javax.swing.JTextArea();
        TreatmentScrlPane = new javax.swing.JScrollPane();
        TreatmentTxt = new javax.swing.JTextArea();
        FollowUpScrlPane = new javax.swing.JScrollPane();
        FollowUpTxt = new javax.swing.JTextArea();
        Complete_HospitalizationSeparator = new javax.swing.JSeparator();
        CancelHospBtn = new javax.swing.JButton();
        PatientIDSelDropdown = new javax.swing.JComboBox<>();
        ReasonHospitalizationScrlPane = new javax.swing.JScrollPane();
        ReasonHospitalizationTxt = new javax.swing.JTextArea();
        PrescriptionPane = new javax.swing.JPanel();
        AppointmentIDSelLabel = new javax.swing.JLabel();
        MedicationNameLabel = new javax.swing.JLabel();
        MedicationNameTxt = new javax.swing.JTextField();
        DoseLabel = new javax.swing.JLabel();
        DoseTxt = new javax.swing.JTextField();
        AdministrationRouteLabel = new javax.swing.JLabel();
        AdministrationRouteTxt = new javax.swing.JTextField();
        FrequencyLabel = new javax.swing.JLabel();
        FrequencyTxt = new javax.swing.JTextField();
        TreatmentDurationLabel = new javax.swing.JLabel();
        TreatmentDurationTxt = new javax.swing.JTextField();
        AdditionalInstructionsLabel = new javax.swing.JLabel();
        AdditionalInstructionsTxt = new javax.swing.JTextField();
        MedicationScrlPane = new javax.swing.JScrollPane();
        MedicationDisplayTable = new javax.swing.JTable();
        AddMedicationButton = new javax.swing.JButton();
        PrescribeMedicationBtn = new javax.swing.JButton();
        AppointmentIDSelDropdown = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        GeneralPane.setRadius(50);

        TitleBar.setRadius(50);
        TitleBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                TitleBarMouseDragged(evt);
            }
        });
        TitleBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TitleBarMousePressed(evt);
            }
        });

        CloseBtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        CloseBtn.setText("X");
        CloseBtn.setBorderPainted(false);
        CloseBtn.setContentAreaFilled(false);
        CloseBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CloseBtn.setFocusable(false);
        CloseBtn.setRequestFocusEnabled(false);
        CloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseBtnActionPerformed(evt);
            }
        });

        TitleLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        TitleLabel.setText("DOCTOR VIEW");

        BackBtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TitleBarLayout = new javax.swing.GroupLayout(TitleBar);
        TitleBar.setLayout(TitleBarLayout);
        TitleBarLayout.setHorizontalGroup(
            TitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TitleBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleLabel)
                .addGap(32, 32, 32)
                .addComponent(BackBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CloseBtn)
                .addGap(19, 19, 19))
        );
        TitleBarLayout.setVerticalGroup(
            TitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(CloseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(BackBtn))
        );

        FilterTotalAppointmentsBtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        FilterTotalAppointmentsBtn.setText("Total appointments");
        FilterTotalAppointmentsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilterTotalAppointmentsBtnActionPerformed(evt);
            }
        });

        AppointmentDisplayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Date", "Patient", "Specialty", "Type", "Status"
            }
        ));
        ScrollableAppointmentsPane.setViewportView(AppointmentDisplayTable);

        FilterPendingAppointmentsBtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        FilterPendingAppointmentsBtn.setText("Pending appointments");
        FilterPendingAppointmentsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilterPendingAppointmentsBtnActionPerformed(evt);
            }
        });

        AppointmentLogoutBtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AppointmentLogoutBtn.setText("Logout");
        AppointmentLogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppointmentLogoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AppointmentPaneLayout = new javax.swing.GroupLayout(AppointmentPane);
        AppointmentPane.setLayout(AppointmentPaneLayout);
        AppointmentPaneLayout.setHorizontalGroup(
            AppointmentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AppointmentPaneLayout.createSequentialGroup()
                .addGroup(AppointmentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AppointmentLogoutBtn)
                    .addGroup(AppointmentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AppointmentPaneLayout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(FilterTotalAppointmentsBtn)
                            .addGap(18, 18, 18)
                            .addComponent(FilterPendingAppointmentsBtn))
                        .addGroup(AppointmentPaneLayout.createSequentialGroup()
                            .addGap(108, 108, 108)
                            .addComponent(ScrollableAppointmentsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1035, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        AppointmentPaneLayout.setVerticalGroup(
            AppointmentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AppointmentPaneLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(AppointmentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FilterTotalAppointmentsBtn)
                    .addComponent(FilterPendingAppointmentsBtn))
                .addGap(18, 18, 18)
                .addComponent(ScrollableAppointmentsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(AppointmentLogoutBtn)
                .addGap(23, 23, 23))
        );

        TabbedPane.addTab("Appointments visualization", AppointmentPane);

        PatientSelectDropdown.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PatientSelectDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        PatientLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PatientLabel.setText("Patient");

        HistoricalAppointmentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Date", "Doctor", "Specialty", "Type", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ScrollableHistoricalAppointmentsPane.setViewportView(HistoricalAppointmentsTable);

        SearchBtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        SearchBtn.setText("Search");
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HistoricalAppointmentsPaneLayout = new javax.swing.GroupLayout(HistoricalAppointmentsPane);
        HistoricalAppointmentsPane.setLayout(HistoricalAppointmentsPaneLayout);
        HistoricalAppointmentsPaneLayout.setHorizontalGroup(
            HistoricalAppointmentsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HistoricalAppointmentsPaneLayout.createSequentialGroup()
                .addGroup(HistoricalAppointmentsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HistoricalAppointmentsPaneLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(PatientLabel)
                        .addGap(18, 18, 18)
                        .addComponent(PatientSelectDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HistoricalAppointmentsPaneLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(ScrollableHistoricalAppointmentsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HistoricalAppointmentsPaneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(SearchBtn)
                .addGap(601, 601, 601))
        );
        HistoricalAppointmentsPaneLayout.setVerticalGroup(
            HistoricalAppointmentsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HistoricalAppointmentsPaneLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(HistoricalAppointmentsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PatientLabel)
                    .addComponent(PatientSelectDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ScrollableHistoricalAppointmentsPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(SearchBtn)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        TabbedPane.addTab("History Appointments of a patient", HistoricalAppointmentsPane);

        FirstNameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        FirstNameLabel.setText("Firstname");

        FirstNameTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        LastNameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        LastNameLabel.setText("Lastname");

        LastNameTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        SpecialtyLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        SpecialtyLabel.setText("Specialty");

        LicenseNumberLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        LicenseNumberLabel.setText("License Number");

        LicenseNumberTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        OfficeLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        OfficeLabel.setText("Assigned office");

        UserNameRegistrationTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        UserNameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        UserNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserNameLabel.setText("User");

        OfficeTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        PasswdTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        PasswdLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PasswdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PasswdLabel.setText("Password");

        PasswdConfLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PasswdConfLabel.setText("Password confirmation");

        PasswdConfTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        SpecialtyDropdown.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        SpecialtyDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "General Medicine", "Cardiology", "Pediatrics", "Neurology", "Traumatology & Orthopedics", "Gynecology & Obstetrics", "Dermatology", "Psychiatry", "Oncology", "Ophthalmology", "Internal Medicine" }));

        RegisterBtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        RegisterBtn.setText("Save");
        RegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InfoEditingPaneLayout = new javax.swing.GroupLayout(InfoEditingPane);
        InfoEditingPane.setLayout(InfoEditingPaneLayout);
        InfoEditingPaneLayout.setHorizontalGroup(
            InfoEditingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoEditingPaneLayout.createSequentialGroup()
                .addGroup(InfoEditingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InfoEditingPaneLayout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(FirstNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(FirstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LastNameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(LastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SpecialtyLabel)
                        .addGap(18, 18, 18)
                        .addComponent(SpecialtyDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InfoEditingPaneLayout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(LicenseNumberLabel)
                        .addGap(18, 18, 18)
                        .addComponent(LicenseNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(OfficeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(OfficeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InfoEditingPaneLayout.createSequentialGroup()
                        .addGap(558, 558, 558)
                        .addGroup(InfoEditingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PasswdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(InfoEditingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(UserNameRegistrationTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                .addComponent(UserNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PasswdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(InfoEditingPaneLayout.createSequentialGroup()
                        .addGap(521, 521, 521)
                        .addComponent(PasswdConfLabel))
                    .addGroup(InfoEditingPaneLayout.createSequentialGroup()
                        .addGap(576, 576, 576)
                        .addComponent(RegisterBtn))
                    .addGroup(InfoEditingPaneLayout.createSequentialGroup()
                        .addGap(561, 561, 561)
                        .addComponent(PasswdConfTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(269, Short.MAX_VALUE))
        );
        InfoEditingPaneLayout.setVerticalGroup(
            InfoEditingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoEditingPaneLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(InfoEditingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameLabel)
                    .addComponent(FirstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastNameLabel)
                    .addComponent(LastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpecialtyLabel)
                    .addComponent(SpecialtyDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(InfoEditingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LicenseNumberLabel)
                    .addComponent(LicenseNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OfficeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OfficeLabel))
                .addGap(30, 30, 30)
                .addComponent(UserNameLabel)
                .addGap(18, 18, 18)
                .addComponent(UserNameRegistrationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PasswdLabel)
                .addGap(27, 27, 27)
                .addComponent(PasswdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PasswdConfLabel)
                .addGap(18, 18, 18)
                .addComponent(PasswdConfTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(RegisterBtn)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Modify info", InfoEditingPane);

        AppointmentIDLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AppointmentIDLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AppointmentIDLabel.setText("Appointment ID");

        AcceptAppointmentSectionLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AcceptAppointmentSectionLabel.setText("Accept medical appointment");

        AcceptAppointmentSelectorDropdown.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AcceptAppointmentSelectorDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        Accept_RescheduleSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        AcceptanceAppointmentBtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AcceptanceAppointmentBtn.setText("Accept");
        AcceptanceAppointmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptanceAppointmentBtnActionPerformed(evt);
            }
        });

        ReschulingAppointmentLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        ReschulingAppointmentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReschulingAppointmentLabel.setText("Reschedule medical appointment");

        RescheduleAppointmentSelectorLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        RescheduleAppointmentSelectorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RescheduleAppointmentSelectorLabel.setText("Appointment");

        RescheduleAppointmentDropdown.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        RescheduleAppointmentDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        AppointmentReschedulingBtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AppointmentReschedulingBtn.setText("Accept");
        AppointmentReschedulingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppointmentReschedulingBtnActionPerformed(evt);
            }
        });

        NewTImeLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        NewTImeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NewTImeLabel.setText("New time appointment");

        NewTimeTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        ReasonLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        ReasonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReasonLabel.setText("Reason for appointment");

        ReasonTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        Reschedule_CompleteSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        CompletingAppointmentLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        CompletingAppointmentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CompletingAppointmentLabel.setText("Complete medical appointment");

        CompleteAppointmentSelectorLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        CompleteAppointmentSelectorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CompleteAppointmentSelectorLabel.setText("Appointment");

        CompleteAppointmentSelectorDropdown.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        CompleteAppointmentSelectorDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        DiagnosisLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        DiagnosisLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DiagnosisLabel.setText("Diagnosis");

        AppointmentObservationsLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AppointmentObservationsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AppointmentObservationsLabel.setText("Observations");

        RecTreatmentLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        RecTreatmentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RecTreatmentLabel.setText("Recommended treatment");

        FollowUpLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        FollowUpLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FollowUpLabel.setText("Follow-up indication");

        CompleteAppointmentBtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        CompleteAppointmentBtn.setText("Complete");
        CompleteAppointmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompleteAppointmentBtnActionPerformed(evt);
            }
        });

        HospitalizationLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        HospitalizationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HospitalizationLabel.setText("Hospitalization");

        ReasonHospitalizationLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        ReasonHospitalizationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReasonHospitalizationLabel.setText("Reason for hospitalization");

        HospStartDateLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        HospStartDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HospStartDateLabel.setText("Date of entry");

        HospStartDateTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        HospDurationLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        HospDurationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HospDurationLabel.setText("Estimated duration");

        HospDurationTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        HospObservationsLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        HospObservationsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HospObservationsLabel.setText("Observations");

        HospObservationsTxt.setColumns(20);
        HospObservationsTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        HospObservationsTxt.setRows(5);
        HospObservationsScrlPane.setViewportView(HospObservationsTxt);

        GenerateHospBtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        GenerateHospBtn.setText("Generate");
        GenerateHospBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateHospBtnActionPerformed(evt);
            }
        });

        RequestSelectDropdown.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        RequestSelectDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        RequestSelBtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        RequestSelBtn.setText("Requests");

        PatientIDSelBtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PatientIDSelBtn.setText("Patient ID");

        DiagnosisTxt.setColumns(20);
        DiagnosisTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        DiagnosisTxt.setRows(5);
        DiagnosisScrlPane.setViewportView(DiagnosisTxt);

        AppointmentObservationsTxt.setColumns(20);
        AppointmentObservationsTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AppointmentObservationsTxt.setRows(5);
        AppointmentObservationsScrlPane.setViewportView(AppointmentObservationsTxt);

        TreatmentTxt.setColumns(20);
        TreatmentTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        TreatmentTxt.setRows(5);
        TreatmentScrlPane.setViewportView(TreatmentTxt);

        FollowUpTxt.setColumns(20);
        FollowUpTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        FollowUpTxt.setRows(5);
        FollowUpScrlPane.setViewportView(FollowUpTxt);

        Complete_HospitalizationSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        CancelHospBtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        CancelHospBtn.setText("Cancel");
        CancelHospBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelHospBtnActionPerformed(evt);
            }
        });

        PatientIDSelDropdown.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PatientIDSelDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        ReasonHospitalizationTxt.setColumns(20);
        ReasonHospitalizationTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        ReasonHospitalizationTxt.setRows(5);
        ReasonHospitalizationScrlPane.setViewportView(ReasonHospitalizationTxt);

        javax.swing.GroupLayout AppointmentMgmtPaneLayout = new javax.swing.GroupLayout(AppointmentMgmtPane);
        AppointmentMgmtPane.setLayout(AppointmentMgmtPaneLayout);
        AppointmentMgmtPaneLayout.setHorizontalGroup(
            AppointmentMgmtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AppointmentMgmtPaneLayout.createSequentialGroup()
                .addGroup(AppointmentMgmtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AppointmentMgmtPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(AppointmentMgmtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AppointmentMgmtPaneLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(AppointmentMgmtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AppointmentMgmtPaneLayout.createSequentialGroup()
                                        .addComponent(AcceptanceAppointmentBtn)
                                        .addGap(87, 87, 87))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AppointmentMgmtPaneLayout.createSequentialGroup()
                                        .addComponent(AcceptAppointmentSelectorDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(67, 67, 67))))
                            .addComponent(AppointmentIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(Accept_RescheduleSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(AppointmentMgmtPaneLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(AcceptAppointmentSectionLabel)
                        .addGap(22, 22, 22)))
                .addGroup(AppointmentMgmtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ReschulingAppointmentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AppointmentMgmtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(RescheduleAppointmentSelectorLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NewTImeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ReasonLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(AppointmentMgmtPaneLayout.createSequentialGroup()
                            .addGroup(AppointmentMgmtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(AppointmentMgmtPaneLayout.createSequentialGroup()
                                    .addGap(90, 90, 90)
                                    .addComponent(RescheduleAppointmentDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(AppointmentMgmtPaneLayout.createSequentialGroup()
                                    .addGap(99, 99, 99)
                                    .addComponent(NewTimeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(AppointmentMgmtPaneLayout.createSequentialGroup()
                                    .addGap(98, 98, 98)
                                    .addComponent(ReasonTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(AppointmentMgmtPaneLayout.createSequentialGroup()
                                    .addGap(112, 112, 112)
                                    .addComponent(AppointmentReschedulingBtn)))
                            .addGap(91, 91, 91))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Reschedule_CompleteSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(AppointmentMgmtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AppointmentMgmtPaneLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(CompleteAppointmentBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(AppointmentMgmtPaneLayout.createSequentialGroup()
                        .addGroup(AppointmentMgmtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AppointmentMgmtPaneLayout.createSequentialGroup()
                                .addGroup(AppointmentMgmtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AppointmentMgmtPaneLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(AppointmentMgmtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(CompleteAppointmentSelectorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CompletingAppointmentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(AppointmentMgmtPaneLayout.createSequentialGroup()
                                        .addGap(99, 99, 99)
                                        .addComponent(CompleteAppointmentSelectorDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 25, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AppointmentMgmtPaneLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(AppointmentMgmtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DiagnosisLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AppointmentObservationsLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(AppointmentMgmtPaneLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(AppointmentMgmtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(FollowUpLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(RecTreatmentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(AppointmentMgmtPaneLayout.createSequentialGroup()
                                .addGroup(AppointmentMgmtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(AppointmentMgmtPaneLayout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(DiagnosisScrlPane, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(AppointmentMgmtPaneLayout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(AppointmentObservationsScrlPane, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(AppointmentMgmtPaneLayout.createSequentialGroup()
                                .addGroup(AppointmentMgmtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(AppointmentMgmtPaneLayout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(TreatmentScrlPane, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(AppointmentMgmtPaneLayout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(FollowUpScrlPane, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(Complete_HospitalizationSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(AppointmentMgmtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AppointmentMgmtPaneLayout.createSequentialGroup()
                        .addGroup(AppointmentMgmtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AppointmentMgmtPaneLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(AppointmentMgmtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(HospitalizationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(HospStartDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(HospDurationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(HospObservationsLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(AppointmentMgmtPaneLayout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addGroup(AppointmentMgmtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(HospStartDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HospDurationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(AppointmentMgmtPaneLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(AppointmentMgmtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(AppointmentMgmtPaneLayout.createSequentialGroup()
                                .addComponent(CancelHospBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(GenerateHospBtn))
                            .addComponent(HospObservationsScrlPane, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(56, Short.MAX_VALUE))
                    .addGroup(AppointmentMgmtPaneLayout.createSequentialGroup()
                        .addGroup(AppointmentMgmtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AppointmentMgmtPaneLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(RequestSelectDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AppointmentMgmtPaneLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(RequestSelBtn)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(AppointmentMgmtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AppointmentMgmtPaneLayout.createSequentialGroup()
                                .addComponent(PatientIDSelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AppointmentMgmtPaneLayout.createSequentialGroup()
                                .addComponent(PatientIDSelDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))))
                    .addGroup(AppointmentMgmtPaneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ReasonHospitalizationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AppointmentMgmtPaneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ReasonHospitalizationScrlPane, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))))
        );
        AppointmentMgmtPaneLayout.setVerticalGroup(
            AppointmentMgmtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Accept_RescheduleSeparator)
            .addGroup(AppointmentMgmtPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AppointmentMgmtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Reschedule_CompleteSeparator)
                    .addGroup(AppointmentMgmtPaneLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(CompletingAppointmentLabel)
                        .addGap(10, 10, 10)
                        .addComponent(CompleteAppointmentSelectorLabel)
                        .addGap(18, 18, 18)
                        .addComponent(CompleteAppointmentSelectorDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DiagnosisLabel)
                        .addGap(18, 18, 18)
                        .addComponent(DiagnosisScrlPane, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AppointmentObservationsLabel)
                        .addGap(18, 18, 18)
                        .addComponent(AppointmentObservationsScrlPane, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RecTreatmentLabel)
                        .addGap(18, 18, 18)
                        .addComponent(TreatmentScrlPane, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FollowUpLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FollowUpScrlPane, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CompleteAppointmentBtn)
                        .addGap(12, 12, 12))
                    .addGroup(AppointmentMgmtPaneLayout.createSequentialGroup()
                        .addGroup(AppointmentMgmtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AppointmentMgmtPaneLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(AcceptAppointmentSectionLabel)
                                .addGap(18, 18, 18)
                                .addComponent(AppointmentIDLabel)
                                .addGap(18, 18, 18)
                                .addComponent(AcceptAppointmentSelectorDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(AcceptanceAppointmentBtn))
                            .addGroup(AppointmentMgmtPaneLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(ReschulingAppointmentLabel)
                                .addGap(18, 18, 18)
                                .addComponent(RescheduleAppointmentSelectorLabel)
                                .addGap(18, 18, 18)
                                .addComponent(RescheduleAppointmentDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(NewTImeLabel)
                                .addGap(18, 18, 18)
                                .addComponent(NewTimeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ReasonLabel)
                                .addGap(18, 18, 18)
                                .addComponent(ReasonTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(AppointmentReschedulingBtn)))
                        .addGap(18, 18, Short.MAX_VALUE))))
            .addGroup(AppointmentMgmtPaneLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(HospitalizationLabel)
                .addGap(18, 18, 18)
                .addGroup(AppointmentMgmtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RequestSelBtn)
                    .addComponent(PatientIDSelBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AppointmentMgmtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RequestSelectDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PatientIDSelDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ReasonHospitalizationLabel)
                .addGap(16, 16, 16)
                .addComponent(ReasonHospitalizationScrlPane, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HospStartDateLabel)
                .addGap(18, 18, 18)
                .addComponent(HospStartDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(HospDurationLabel)
                .addGap(18, 18, 18)
                .addComponent(HospDurationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(HospObservationsLabel)
                .addGap(18, 18, 18)
                .addComponent(HospObservationsScrlPane, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(AppointmentMgmtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenerateHospBtn)
                    .addComponent(CancelHospBtn))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(Complete_HospitalizationSeparator, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        TabbedPane.addTab("Request/Appointments", AppointmentMgmtPane);

        AppointmentIDSelLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AppointmentIDSelLabel.setText("Appointment ID");

        MedicationNameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        MedicationNameLabel.setText("Medication name");

        MedicationNameTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        DoseLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        DoseLabel.setText("Dose");

        DoseTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        AdministrationRouteLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AdministrationRouteLabel.setText("Administration route");

        AdministrationRouteTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        FrequencyLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        FrequencyLabel.setText("Frecuency");

        FrequencyTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        TreatmentDurationLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        TreatmentDurationLabel.setText("Treatment duration");

        TreatmentDurationTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        AdditionalInstructionsLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AdditionalInstructionsLabel.setText("Additional instructions");

        AdditionalInstructionsTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        MedicationDisplayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Appointment ID", "Medication name", "Dose", "Administration route", "Treatment duration", "Additional instructions", "Frecuency"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        MedicationScrlPane.setViewportView(MedicationDisplayTable);

        AddMedicationButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AddMedicationButton.setText("Add");
        AddMedicationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddMedicationButtonActionPerformed(evt);
            }
        });

        PrescribeMedicationBtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PrescribeMedicationBtn.setText("Prescribe");
        PrescribeMedicationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrescribeMedicationBtnActionPerformed(evt);
            }
        });

        AppointmentIDSelDropdown.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AppointmentIDSelDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        javax.swing.GroupLayout PrescriptionPaneLayout = new javax.swing.GroupLayout(PrescriptionPane);
        PrescriptionPane.setLayout(PrescriptionPaneLayout);
        PrescriptionPaneLayout.setHorizontalGroup(
            PrescriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrescriptionPaneLayout.createSequentialGroup()
                .addGroup(PrescriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PrescriptionPaneLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(PrescriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MedicationScrlPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PrescriptionPaneLayout.createSequentialGroup()
                                .addGroup(PrescriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PrescriptionPaneLayout.createSequentialGroup()
                                        .addComponent(AppointmentIDSelLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(AppointmentIDSelDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9)
                                        .addComponent(MedicationNameLabel))
                                    .addGroup(PrescriptionPaneLayout.createSequentialGroup()
                                        .addComponent(TreatmentDurationLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TreatmentDurationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PrescriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(PrescriptionPaneLayout.createSequentialGroup()
                                        .addComponent(AdditionalInstructionsLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(AdditionalInstructionsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(FrequencyLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(FrequencyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PrescriptionPaneLayout.createSequentialGroup()
                                        .addComponent(MedicationNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(DoseLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(DoseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(AdministrationRouteLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(AdministrationRouteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AddMedicationButton))))
                    .addGroup(PrescriptionPaneLayout.createSequentialGroup()
                        .addGap(583, 583, 583)
                        .addComponent(PrescribeMedicationBtn)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        PrescriptionPaneLayout.setVerticalGroup(
            PrescriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrescriptionPaneLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(PrescriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AppointmentIDSelLabel)
                    .addComponent(MedicationNameLabel)
                    .addComponent(MedicationNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DoseLabel)
                    .addComponent(DoseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdministrationRouteLabel)
                    .addComponent(AdministrationRouteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddMedicationButton)
                    .addComponent(AppointmentIDSelDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PrescriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TreatmentDurationLabel)
                    .addComponent(TreatmentDurationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdditionalInstructionsLabel)
                    .addComponent(AdditionalInstructionsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FrequencyLabel)
                    .addComponent(FrequencyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(MedicationScrlPane, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(PrescribeMedicationBtn)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Prescribe medications", PrescriptionPane);

        javax.swing.GroupLayout GeneralPaneLayout = new javax.swing.GroupLayout(GeneralPane);
        GeneralPane.setLayout(GeneralPaneLayout);
        GeneralPaneLayout.setHorizontalGroup(
            GeneralPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeneralPaneLayout.createSequentialGroup()
                .addGroup(GeneralPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TitleBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TabbedPane))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        GeneralPaneLayout.setVerticalGroup(
            GeneralPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeneralPaneLayout.createSequentialGroup()
                .addComponent(TitleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TabbedPane))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GeneralPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GeneralPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TitleBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TitleBarMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_TitleBarMousePressed

    private void TitleBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TitleBarMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_TitleBarMouseDragged

    private void CloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_CloseBtnActionPerformed

    private void FilterPendingAppointmentsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilterPendingAppointmentsBtnActionPerformed
        // TODO add your handling code here:
        FilterTotalAppointmentsBtn.setSelected(false);
        Response response = AppointmentController.getAppointmentsByDoctor(String.valueOf(doctor.getId()), true);
        if (response.getStatus() == Status.OK) {
            DefaultTableModel model = (DefaultTableModel) AppointmentDisplayTable.getModel();
            model.setRowCount(0);
            ArrayList<HashMap<String, Object>> doctorAppointments = response.getDataList();
            for (HashMap<String, Object> appointmentData : doctorAppointments) {
                model.addRow(new Object[]{
                    appointmentData.get("id"),
                    appointmentData.get("datetime"),
                    appointmentData.get("patientName"),
                    appointmentData.get("specialty"),
                    Boolean.TRUE.equals(appointmentData.get("type")) ? "In person" : "Virtual",
                    appointmentData.get("status")
                });
            }
        } else {
            NotificationController.notifyError(response.getMessage(), this);
        }
    }//GEN-LAST:event_FilterPendingAppointmentsBtnActionPerformed

    private void RegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterBtnActionPerformed
        String firstname = FirstNameTxt.getText();
        String lastname = LastNameTxt.getText();
        String spec = SpecialtyDropdown.getItemAt(SpecialtyDropdown.getSelectedIndex());
        String licenseNumber = LicenseNumberTxt.getText();
        String assignedOffice = OfficeTxt.getText();
        String username = UserNameRegistrationTxt.getText();
        String password = PasswdTxt.getText();
        String comPassword = PasswdConfTxt.getText();
        Response response = DoctorController.updateDoctor(
            String.valueOf(user.getId()),
            String.valueOf(doctor.getId()),
            username,
            firstname,
            lastname,
            password,
            comPassword,
            spec,
            licenseNumber,
            assignedOffice
        );

        if (response.getStatus() == Status.OK) {
            NotificationController.notifySuccess(response.getMessage(), this);
        } else if (response.getStatus() == Status.BAD_REQUEST || response.getStatus() == Status.NOT_FOUND) {
            NotificationController.notifyInfo(response.getMessage(), this);
        } else {
            NotificationController.notifyError(response.getMessage(), this);
        }
    }//GEN-LAST:event_RegisterBtnActionPerformed

    private void AppointmentLogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppointmentLogoutBtnActionPerformed
        LoginRegistrationView login = new LoginRegistrationView();
        this.setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_AppointmentLogoutBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        AdminDashboardView admin = new AdminDashboardView(user);
        this.setVisible(false);
        admin.setVisible(true);
    }//GEN-LAST:event_BackBtnActionPerformed

    private void CancelHospBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelHospBtnActionPerformed
        if (RequestSelBtn.isSelected()) {
            String hospId = RequestSelectDropdown.getItemAt(RequestSelectDropdown.getSelectedIndex());
            Response response = HospitalizationController.denyHospitalization(hospId, String.valueOf(doctor.getId()));
            if (response.getStatus() == Status.OK) {
                NotificationController.notifySuccess(response.getMessage(), this);
            } else {
                NotificationController.notifyError(response.getMessage(), this);
            }
        }
    }//GEN-LAST:event_CancelHospBtnActionPerformed

    private void GenerateHospBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateHospBtnActionPerformed
        if (RequestSelBtn.isSelected()) {
            String hospId = RequestSelectDropdown.getItemAt(RequestSelectDropdown.getSelectedIndex());
            Response response = HospitalizationController.approveHospitalization(hospId, String.valueOf(doctor.getId()));
            if (response.getStatus() == Status.OK) {
                NotificationController.notifySuccess(response.getMessage(), this);
            } else {
                NotificationController.notifyError(response.getMessage(), this);
            }
        } else if (PatientIDSelBtn.isSelected()) {
            String patientId = PatientIDSelDropdown.getItemAt(PatientIDSelDropdown.getSelectedIndex());
            String reason = ReasonHospitalizationTxt.getText();
            String observations = HospObservationsTxt.getText();
            String entDate = HospStartDateTxt.getText();
            Response response = HospitalizationController.createHospitalization(patientId, entDate, reason, "IMC");
            if (response.getStatus() == Status.CREATED) {
                // If created, doctor automatically approves it to assign themselves
                String newHospId = response.getData().get("hospitalizationId").toString();
                HospitalizationController.approveHospitalization(newHospId, String.valueOf(doctor.getId()));
                NotificationController.notifySuccess("Direct Hospitalization created and assigned.", this);
            } else {
                NotificationController.notifyError(response.getMessage(), this);
            }
        }
    }//GEN-LAST:event_GenerateHospBtnActionPerformed

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        // TODO add your handling code here:
        String selected = PatientSelectDropdown.getItemAt(PatientSelectDropdown.getSelectedIndex());
        if (selected == null || "Select one".equals(selected)){
            NotificationController.notifyError("Please select a patient first.", this);
        } else {
            Response response = AppointmentController.getAppointmentsByPatient(selected);
            if (response.getStatus() == Status.OK) {
                DefaultTableModel model = (DefaultTableModel) HistoricalAppointmentsTable.getModel();
                model.setRowCount(0);
                ArrayList<HashMap<String, Object>> patientAppointments = response.getDataList();
                for (HashMap<String, Object> appointmentData : patientAppointments) {
                    model.addRow(new Object[]{
                        appointmentData.get("id"),
                        appointmentData.get("datetime"),
                        appointmentData.get("doctorName"),
                        appointmentData.get("specialty"),
                        Boolean.TRUE.equals(appointmentData.get("type")) ? "In-person" : "Remote",
                        appointmentData.get("status")
                    });
                }
            } else {
                NotificationController.notifyError(response.getMessage(), this);
            }
        }
    }//GEN-LAST:event_SearchBtnActionPerformed

    private void FilterTotalAppointmentsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilterTotalAppointmentsBtnActionPerformed
        // TODO add your handling code here:
        FilterPendingAppointmentsBtn.setSelected(false);
        Response response = AppointmentController.getAppointmentsByDoctor(String.valueOf(doctor.getId()), false);
        if (response.getStatus() == Status.OK) {
            DefaultTableModel model = (DefaultTableModel) AppointmentDisplayTable.getModel();
            model.setRowCount(0);
            ArrayList<HashMap<String, Object>> doctorAppointments = response.getDataList();
            for (HashMap<String, Object> appointmentData : doctorAppointments) {
                model.addRow(new Object[]{
                    appointmentData.get("id"),
                    appointmentData.get("datetime"),
                    appointmentData.get("patientName"),
                    appointmentData.get("specialty"),
                    Boolean.TRUE.equals(appointmentData.get("type")) ? "In person" : "Remote",
                    appointmentData.get("status")
                });
            }
        } else {
            NotificationController.notifyError(response.getMessage(), this);
        }
    }//GEN-LAST:event_FilterTotalAppointmentsBtnActionPerformed

    private void AcceptanceAppointmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptanceAppointmentBtnActionPerformed
        String idAppointment = AcceptAppointmentSelectorDropdown.getItemAt(AcceptAppointmentSelectorDropdown.getSelectedIndex());
        Response response = AppointmentController.acceptAppointment(idAppointment, String.valueOf(doctor.getId()));
        if (response.getStatus() == Status.OK) {
            NotificationController.notifySuccess(response.getMessage(), this);
        } else {
            NotificationController.notifyError(response.getMessage(), this);
        }
    }//GEN-LAST:event_AcceptanceAppointmentBtnActionPerformed

    private void CompleteAppointmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompleteAppointmentBtnActionPerformed
        String idAppointment = CompleteAppointmentSelectorDropdown.getItemAt(CompleteAppointmentSelectorDropdown.getSelectedIndex());
        Response response = AppointmentController.completeAppointment(
            idAppointment,
            String.valueOf(doctor.getId()),
            DiagnosisTxt.getText(),
            AppointmentObservationsTxt.getText(),
            TreatmentTxt.getText(),
            FollowUpTxt.getText()
        );
        if (response.getStatus() == Status.OK) {
            NotificationController.notifySuccess(response.getMessage(), this);
        } else if (response.getStatus() == Status.BAD_REQUEST || response.getStatus() == Status.NOT_FOUND) {
            NotificationController.notifyInfo(response.getMessage(), this);
        } else {
            NotificationController.notifyError(response.getMessage(), this);
        }
    }//GEN-LAST:event_CompleteAppointmentBtnActionPerformed

    private void PrescribeMedicationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrescribeMedicationBtnActionPerformed
        DefaultTableModel model = (DefaultTableModel) MedicationDisplayTable.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_PrescribeMedicationBtnActionPerformed

    private void AddMedicationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMedicationButtonActionPerformed
        // TODO add your handling code here:
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) MedicationDisplayTable.getModel();
        
        String appointmentId = AppointmentIDSelDropdown.getItemAt(AppointmentIDSelDropdown.getSelectedIndex());
        String medicationName = MedicationNameTxt.getText();
        String doseStr = DoseTxt.getText();
        String durationStr = TreatmentDurationTxt.getText();
        String frequencyStr = FrequencyTxt.getText();
        String administrationRoute = AdministrationRouteTxt.getText();
        String aditionalIformation = AdditionalInstructionsTxt.getText();
        
        Response response = PrescriptionController.addPrescriptionToAppointment(appointmentId, String.valueOf(doctor.getId()), medicationName, doseStr, administrationRoute, durationStr, aditionalIformation, frequencyStr);

        if (response.getStatus() == Status.OK) {
            model.addRow(new Object[]{appointmentId, medicationName, doseStr, administrationRoute, durationStr, aditionalIformation, frequencyStr});
            NotificationController.notifySuccess(response.getMessage(), this);
        } else {
            NotificationController.notifyError(response.getMessage(), this);
        }
    }//GEN-LAST:event_AddMedicationButtonActionPerformed

    private void AppointmentReschedulingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppointmentReschedulingBtnActionPerformed
        String appointmentId = RescheduleAppointmentDropdown.getItemAt(RescheduleAppointmentDropdown.getSelectedIndex());
        String newTimeStr = NewTimeTxt.getText();
        String reasonChangeTime = ReasonTxt.getText();
        Response response = AppointmentController.rescheduleAppointment(appointmentId, String.valueOf(doctor.getId()), newTimeStr, reasonChangeTime);
        if (response.getStatus() == Status.OK) {
            NotificationController.notifySuccess(response.getMessage(), this);
        } else {
            NotificationController.notifyError(response.getMessage(), this);
        }
    }//GEN-LAST:event_AppointmentReschedulingBtnActionPerformed




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AcceptAppointmentSectionLabel;
    private javax.swing.JComboBox<String> AcceptAppointmentSelectorDropdown;
    private javax.swing.JSeparator Accept_RescheduleSeparator;
    private javax.swing.JButton AcceptanceAppointmentBtn;
    private javax.swing.JButton AddMedicationButton;
    private javax.swing.JLabel AdditionalInstructionsLabel;
    private javax.swing.JTextField AdditionalInstructionsTxt;
    private javax.swing.JLabel AdministrationRouteLabel;
    private javax.swing.JTextField AdministrationRouteTxt;
    private javax.swing.JTable AppointmentDisplayTable;
    private javax.swing.JLabel AppointmentIDLabel;
    private javax.swing.JComboBox<String> AppointmentIDSelDropdown;
    private javax.swing.JLabel AppointmentIDSelLabel;
    private javax.swing.JButton AppointmentLogoutBtn;
    private javax.swing.JPanel AppointmentMgmtPane;
    private javax.swing.JLabel AppointmentObservationsLabel;
    private javax.swing.JScrollPane AppointmentObservationsScrlPane;
    private javax.swing.JTextArea AppointmentObservationsTxt;
    private javax.swing.JPanel AppointmentPane;
    private javax.swing.JButton AppointmentReschedulingBtn;
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton CancelHospBtn;
    private javax.swing.JButton CloseBtn;
    private javax.swing.JButton CompleteAppointmentBtn;
    private javax.swing.JComboBox<String> CompleteAppointmentSelectorDropdown;
    private javax.swing.JLabel CompleteAppointmentSelectorLabel;
    private javax.swing.JSeparator Complete_HospitalizationSeparator;
    private javax.swing.JLabel CompletingAppointmentLabel;
    private javax.swing.JLabel DiagnosisLabel;
    private javax.swing.JScrollPane DiagnosisScrlPane;
    private javax.swing.JTextArea DiagnosisTxt;
    private javax.swing.JLabel DoseLabel;
    private javax.swing.JTextField DoseTxt;
    private javax.swing.JRadioButton FilterPendingAppointmentsBtn;
    private javax.swing.JRadioButton FilterTotalAppointmentsBtn;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JTextField FirstNameTxt;
    private javax.swing.JLabel FollowUpLabel;
    private javax.swing.JScrollPane FollowUpScrlPane;
    private javax.swing.JTextArea FollowUpTxt;
    private javax.swing.JLabel FrequencyLabel;
    private javax.swing.JTextField FrequencyTxt;
    private com.ospedale.view.PanelRound GeneralPane;
    private javax.swing.JButton GenerateHospBtn;
    private javax.swing.JPanel HistoricalAppointmentsPane;
    private javax.swing.JTable HistoricalAppointmentsTable;
    private javax.swing.JLabel HospDurationLabel;
    private javax.swing.JTextField HospDurationTxt;
    private javax.swing.JLabel HospObservationsLabel;
    private javax.swing.JScrollPane HospObservationsScrlPane;
    private javax.swing.JTextArea HospObservationsTxt;
    private javax.swing.JLabel HospStartDateLabel;
    private javax.swing.JTextField HospStartDateTxt;
    private javax.swing.JLabel HospitalizationLabel;
    private javax.swing.JPanel InfoEditingPane;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JTextField LastNameTxt;
    private javax.swing.JLabel LicenseNumberLabel;
    private javax.swing.JTextField LicenseNumberTxt;
    private javax.swing.JTable MedicationDisplayTable;
    private javax.swing.JLabel MedicationNameLabel;
    private javax.swing.JTextField MedicationNameTxt;
    private javax.swing.JScrollPane MedicationScrlPane;
    private javax.swing.JLabel NewTImeLabel;
    private javax.swing.JTextField NewTimeTxt;
    private javax.swing.JLabel OfficeLabel;
    private javax.swing.JTextField OfficeTxt;
    private javax.swing.JLabel PasswdConfLabel;
    private javax.swing.JTextField PasswdConfTxt;
    private javax.swing.JLabel PasswdLabel;
    private javax.swing.JTextField PasswdTxt;
    private javax.swing.JRadioButton PatientIDSelBtn;
    private javax.swing.JComboBox<String> PatientIDSelDropdown;
    private javax.swing.JLabel PatientLabel;
    private javax.swing.JComboBox<String> PatientSelectDropdown;
    private javax.swing.JButton PrescribeMedicationBtn;
    private javax.swing.JPanel PrescriptionPane;
    private javax.swing.JLabel ReasonHospitalizationLabel;
    private javax.swing.JScrollPane ReasonHospitalizationScrlPane;
    private javax.swing.JTextArea ReasonHospitalizationTxt;
    private javax.swing.JLabel ReasonLabel;
    private javax.swing.JTextField ReasonTxt;
    private javax.swing.JLabel RecTreatmentLabel;
    private javax.swing.JButton RegisterBtn;
    private javax.swing.JRadioButton RequestSelBtn;
    private javax.swing.JComboBox<String> RequestSelectDropdown;
    private javax.swing.JComboBox<String> RescheduleAppointmentDropdown;
    private javax.swing.JLabel RescheduleAppointmentSelectorLabel;
    private javax.swing.JSeparator Reschedule_CompleteSeparator;
    private javax.swing.JLabel ReschulingAppointmentLabel;
    private javax.swing.JScrollPane ScrollableAppointmentsPane;
    private javax.swing.JScrollPane ScrollableHistoricalAppointmentsPane;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JComboBox<String> SpecialtyDropdown;
    private javax.swing.JLabel SpecialtyLabel;
    private javax.swing.JTabbedPane TabbedPane;
    private com.ospedale.view.PanelRound TitleBar;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JLabel TreatmentDurationLabel;
    private javax.swing.JTextField TreatmentDurationTxt;
    private javax.swing.JScrollPane TreatmentScrlPane;
    private javax.swing.JTextArea TreatmentTxt;
    private javax.swing.JLabel UserNameLabel;
    private javax.swing.JTextField UserNameRegistrationTxt;
    // End of variables declaration//GEN-END:variables
}
