/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ospedale.view;

import com.formdev.flatlaf.FlatDarkLaf;
import com.ospedale.controller.AuthenticationController;
import com.ospedale.controller.NotificationController;
import com.ospedale.controller.utils.Response;
import com.ospedale.controller.utils.Status;
import java.awt.Color;
import java.time.LocalDate;
import java.time.Month;
import java.util.ArrayList;
import javax.swing.UIManager;
import com.ospedale.model.Administrator;
import com.ospedale.model.Appointment;
import com.ospedale.model.Doctor;
import com.ospedale.model.Hospitalization;
import com.ospedale.model.Patient;
import com.ospedale.model.User;

/**
 *
 * @author jjlora
 * @author edangulo
 */
public class LoginRegistrationView extends javax.swing.JFrame {

    private int x, y;
    private final NotificationController notificationController;
    private ArrayList<User> users;
    private ArrayList<Hospitalization> hospitalizations;
    private ArrayList<Appointment> appointments;

    public LoginRegistrationView() {
        
        this.notificationController = new NotificationController();
        initComponents();
        this.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);

        this.users = new ArrayList<>();
        this.users.add(new Administrator(0, "admin", "admin", "adnim", "admin123"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GeneralPane = new com.ospedale.view.PanelRound();
        ToolBar = new com.ospedale.view.PanelRound();
        CloseBtn = new javax.swing.JButton();
        TabbedPane = new javax.swing.JTabbedPane();
        LoginPane = new com.ospedale.view.PanelRound();
        LoginLabel = new javax.swing.JLabel();
        UserNameLoginTxt = new javax.swing.JTextField();
        UserNameLoginLabel = new javax.swing.JLabel();
        PasswdLoginTxt = new javax.swing.JTextField();
        PasswdLoginLabel = new javax.swing.JLabel();
        LoginBtn = new javax.swing.JButton();
        PatientRegisterPane = new javax.swing.JPanel();
        FirstNameLabel = new javax.swing.JLabel();
        FirstNameTxt = new javax.swing.JTextField();
        LastNameLabel = new javax.swing.JLabel();
        LastNameTxt = new javax.swing.JTextField();
        IDLabel = new javax.swing.JLabel();
        IDTxt = new javax.swing.JTextField();
        GenderLabel = new javax.swing.JLabel();
        PhoneLabel = new javax.swing.JLabel();
        PhoneTxt = new javax.swing.JTextField();
        EmailLabel = new javax.swing.JLabel();
        EmailTxt = new javax.swing.JTextField();
        UserNameRegistrationLabel = new javax.swing.JLabel();
        UserNameRegistrationTxt = new javax.swing.JTextField();
        PasswdRegistrationTxt = new javax.swing.JTextField();
        PasswdRegistrationLabel = new javax.swing.JLabel();
        PasswdConfLabel = new javax.swing.JLabel();
        PasswdConfTxt = new javax.swing.JTextField();
        GenderDropdown = new javax.swing.JComboBox<>();
        RegistrationBtn = new javax.swing.JButton();
        AddressLabel = new javax.swing.JLabel();
        AddressTxt = new javax.swing.JTextField();
        BirthdateLabel = new javax.swing.JLabel();
        BirthdateTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        GeneralPane.setRadius(50);

        ToolBar.setRadius(50);
        ToolBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                ToolBarMouseDragged(evt);
            }
        });
        ToolBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ToolBarMousePressed(evt);
            }
        });

        CloseBtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        CloseBtn.setText("X");
        CloseBtn.setBorderPainted(false);
        CloseBtn.setContentAreaFilled(false);
        CloseBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CloseBtn.setFocusable(false);
        CloseBtn.setRequestFocusEnabled(false);
        CloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ToolBarLayout = new javax.swing.GroupLayout(ToolBar);
        ToolBar.setLayout(ToolBarLayout);
        ToolBarLayout.setHorizontalGroup(
            ToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ToolBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CloseBtn)
                .addGap(19, 19, 19))
        );
        ToolBarLayout.setVerticalGroup(
            ToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CloseBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        LoginLabel.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        LoginLabel.setText("LOGIN");

        UserNameLoginTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        UserNameLoginTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        UserNameLoginLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        UserNameLoginLabel.setText("USERNAME");

        PasswdLoginTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PasswdLoginTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        PasswdLoginLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PasswdLoginLabel.setText("PASSWORD");

        LoginBtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        LoginBtn.setText("ENTER");
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginPaneLayout = new javax.swing.GroupLayout(LoginPane);
        LoginPane.setLayout(LoginPaneLayout);
        LoginPaneLayout.setHorizontalGroup(
            LoginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPaneLayout.createSequentialGroup()
                .addContainerGap(475, Short.MAX_VALUE)
                .addComponent(LoginLabel)
                .addGap(481, 481, 481))
            .addGroup(LoginPaneLayout.createSequentialGroup()
                .addGroup(LoginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPaneLayout.createSequentialGroup()
                        .addGap(431, 431, 431)
                        .addGroup(LoginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPaneLayout.createSequentialGroup()
                                .addGroup(LoginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PasswdLoginLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(UserNameLoginLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(PasswdLoginTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(UserNameLoginTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(LoginPaneLayout.createSequentialGroup()
                        .addGap(471, 471, 471)
                        .addComponent(LoginBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LoginPaneLayout.setVerticalGroup(
            LoginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPaneLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(LoginLabel)
                .addGap(74, 74, 74)
                .addComponent(UserNameLoginLabel)
                .addGap(18, 18, 18)
                .addComponent(UserNameLoginTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PasswdLoginLabel)
                .addGap(18, 18, 18)
                .addComponent(PasswdLoginTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(LoginBtn)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Login", LoginPane);

        FirstNameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        FirstNameLabel.setText("Firstname");

        FirstNameTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        LastNameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        LastNameLabel.setText("Lastname");

        LastNameTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        IDLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        IDLabel.setText("ID");

        IDTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        GenderLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        GenderLabel.setText("Gender");

        PhoneLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PhoneLabel.setText("Phone");

        PhoneTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        EmailLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        EmailLabel.setText("Email");

        EmailTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        UserNameRegistrationLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        UserNameRegistrationLabel.setText("User");

        UserNameRegistrationTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        PasswdRegistrationTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        PasswdRegistrationLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PasswdRegistrationLabel.setText("Password");

        PasswdConfLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PasswdConfLabel.setText("Password confirmation");

        PasswdConfTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PasswdConfTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswdConfTxtActionPerformed(evt);
            }
        });

        GenderDropdown.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        GenderDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Female", "Male" }));

        RegistrationBtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        RegistrationBtn.setText("Save");
        RegistrationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrationBtnActionPerformed(evt);
            }
        });

        AddressLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AddressLabel.setText("Address");

        AddressTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        BirthdateLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        BirthdateLabel.setText("Birthdate");

        BirthdateTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout PatientRegisterPaneLayout = new javax.swing.GroupLayout(PatientRegisterPane);
        PatientRegisterPane.setLayout(PatientRegisterPaneLayout);
        PatientRegisterPaneLayout.setHorizontalGroup(
            PatientRegisterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PatientRegisterPaneLayout.createSequentialGroup()
                .addGroup(PatientRegisterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PatientRegisterPaneLayout.createSequentialGroup()
                        .addGap(450, 450, 450)
                        .addComponent(PasswdRegistrationLabel))
                    .addGroup(PatientRegisterPaneLayout.createSequentialGroup()
                        .addGap(434, 434, 434)
                        .addGroup(PatientRegisterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UserNameRegistrationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PasswdRegistrationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PatientRegisterPaneLayout.createSequentialGroup()
                        .addGap(473, 473, 473)
                        .addComponent(UserNameRegistrationLabel))
                    .addGroup(PatientRegisterPaneLayout.createSequentialGroup()
                        .addGap(432, 432, 432)
                        .addComponent(PasswdConfTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PatientRegisterPaneLayout.createSequentialGroup()
                        .addGap(456, 456, 456)
                        .addComponent(RegistrationBtn))
                    .addGroup(PatientRegisterPaneLayout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(PasswdConfLabel))
                    .addGroup(PatientRegisterPaneLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(PatientRegisterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(PatientRegisterPaneLayout.createSequentialGroup()
                                .addComponent(BirthdateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BirthdateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PatientRegisterPaneLayout.createSequentialGroup()
                                .addComponent(FirstNameLabel)
                                .addGap(34, 34, 34)
                                .addComponent(FirstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(PatientRegisterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LastNameLabel)
                            .addComponent(AddressLabel))
                        .addGap(18, 18, 18)
                        .addGroup(PatientRegisterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PatientRegisterPaneLayout.createSequentialGroup()
                                .addComponent(LastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(IDLabel)
                                .addGap(30, 30, 30)
                                .addComponent(IDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(GenderLabel)
                                .addGap(26, 26, 26)
                                .addComponent(GenderDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PatientRegisterPaneLayout.createSequentialGroup()
                                .addComponent(AddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(PhoneLabel)
                                .addGap(18, 18, 18)
                                .addComponent(PhoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EmailLabel)
                                .addGap(18, 18, 18)
                                .addComponent(EmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        PatientRegisterPaneLayout.setVerticalGroup(
            PatientRegisterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PatientRegisterPaneLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PatientRegisterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameLabel)
                    .addComponent(FirstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastNameLabel)
                    .addComponent(LastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDLabel)
                    .addComponent(IDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GenderLabel)
                    .addComponent(GenderDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PatientRegisterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PatientRegisterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BirthdateLabel)
                        .addComponent(BirthdateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AddressLabel)
                        .addComponent(AddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PhoneLabel)
                        .addComponent(PhoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PatientRegisterPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(EmailLabel)
                        .addComponent(EmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(UserNameRegistrationLabel)
                .addGap(18, 18, 18)
                .addComponent(UserNameRegistrationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PasswdRegistrationLabel)
                .addGap(18, 18, 18)
                .addComponent(PasswdRegistrationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PasswdConfLabel)
                .addGap(18, 18, 18)
                .addComponent(PasswdConfTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(RegistrationBtn)
                .addGap(42, 42, 42))
        );

        TabbedPane.addTab("Patient register", PatientRegisterPane);

        javax.swing.GroupLayout GeneralPaneLayout = new javax.swing.GroupLayout(GeneralPane);
        GeneralPane.setLayout(GeneralPaneLayout);
        GeneralPaneLayout.setHorizontalGroup(
            GeneralPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(GeneralPaneLayout.createSequentialGroup()
                .addComponent(TabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1028, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        GeneralPaneLayout.setVerticalGroup(
            GeneralPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeneralPaneLayout.createSequentialGroup()
                .addComponent(ToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TabbedPane)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GeneralPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GeneralPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ToolBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ToolBarMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_ToolBarMousePressed

    private void ToolBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ToolBarMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_ToolBarMouseDragged

    private void CloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_CloseBtnActionPerformed

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        Response response = AuthenticationController.tryAuthenticate(UserNameLoginTxt.getText(), PasswdLoginTxt.getText(), users);
        if (response.getStatus() == Status.OK){
            User user = (User) response.getData().get("user");
            String role = (String) response.getData().get("role");
            notificationController.notifySuccess(response.getMessage(), this);
            
            this.setVisible(false);
            
            switch(role) {
                case "ADMIN":
                    new AdminDashboardView(user, (Doctor) user, users, hospitalizations, appointments).setVisible(true);
                    break;
                case "DOCTOR":
                    new DoctorDashboardView((Doctor) user, users, hospitalizations, appointments).setVisible(true);
                    break;
                case "PATIENT":
                    new PatientDashboardView(user, (Patient) user, users, appointments, hospitalizations).setVisible(true);
                    break;
                default:
                    notificationController.notifyError("Unknown user role.", this);
                    this.setVisible(true);
                    break;
            }
        } else if (response.getStatus() == Status.BAD_REQUEST || response.getStatus() == Status.NOT_FOUND) {
            notificationController.notifyError(response.getMessage(), this);
        } else {
            notificationController.notifyError("Unexpected error: " + response.getMessage(), this);
        }
    }//GEN-LAST:event_LoginBtnActionPerformed

    private void RegistrationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrationBtnActionPerformed
        String firstname = FirstNameTxt.getText();
        String lastname = LastNameTxt.getText();
        long id = Long.parseLong(IDTxt.getText());
        boolean gender = (GenderDropdown.getSelectedIndex() == 0 ? null : (GenderDropdown.getSelectedIndex() == 1 ));
        String birth = BirthdateTxt.getText();
        String address = AddressTxt.getText();
        long phone = Long.parseLong(PhoneTxt.getText());
        String email = EmailTxt.getText();
        String user = UserNameRegistrationTxt.getText();
        String password = PasswdRegistrationTxt.getText();
        String comPassword = PasswdConfTxt.getText();
        LocalDate birthdate = LocalDate.of(Integer.parseInt(birth.substring(0, 4)), Integer.parseInt(birth.substring(5, 7)), Integer.parseInt(birth.substring(8)));
        if (comPassword.equals(password)) {
            users.add(new Patient(id, user, firstname, lastname, password, email, birthdate, gender, phone, address));
        }
        
    }//GEN-LAST:event_RegistrationBtnActionPerformed

    private void PasswdConfTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswdConfTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswdConfTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JTextField AddressTxt;
    private javax.swing.JLabel BirthdateLabel;
    private javax.swing.JTextField BirthdateTxt;
    private javax.swing.JButton CloseBtn;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JTextField EmailTxt;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JTextField FirstNameTxt;
    private javax.swing.JComboBox<String> GenderDropdown;
    private javax.swing.JLabel GenderLabel;
    private com.ospedale.view.PanelRound GeneralPane;
    private javax.swing.JLabel IDLabel;
    private javax.swing.JTextField IDTxt;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JTextField LastNameTxt;
    private javax.swing.JButton LoginBtn;
    private javax.swing.JLabel LoginLabel;
    private com.ospedale.view.PanelRound LoginPane;
    private javax.swing.JLabel PasswdConfLabel;
    private javax.swing.JTextField PasswdConfTxt;
    private javax.swing.JLabel PasswdLoginLabel;
    private javax.swing.JTextField PasswdLoginTxt;
    private javax.swing.JLabel PasswdRegistrationLabel;
    private javax.swing.JTextField PasswdRegistrationTxt;
    private javax.swing.JPanel PatientRegisterPane;
    private javax.swing.JLabel PhoneLabel;
    private javax.swing.JTextField PhoneTxt;
    private javax.swing.JButton RegistrationBtn;
    private javax.swing.JTabbedPane TabbedPane;
    private com.ospedale.view.PanelRound ToolBar;
    private javax.swing.JLabel UserNameLoginLabel;
    private javax.swing.JTextField UserNameLoginTxt;
    private javax.swing.JLabel UserNameRegistrationLabel;
    private javax.swing.JTextField UserNameRegistrationTxt;
    // End of variables declaration//GEN-END:variables
}
