/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ospedale.view;

import java.awt.Color;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import com.ospedale.model.Administrator;
import com.ospedale.model.Appointment;
import com.ospedale.model.AppointmentStatus;
import com.ospedale.controller.AppointmentController;
import com.ospedale.controller.HospitalizationController;
import com.ospedale.model.Doctor;
import com.ospedale.model.Hospitalization;
import com.ospedale.model.Patient;
import com.ospedale.controller.PatientController;
import com.ospedale.model.RoomType;
import com.ospedale.model.Specialty;
import com.ospedale.model.User;
import com.ospedale.model.storage.Storage;
import com.ospedale.controller.utils.Response;
import com.ospedale.controller.utils.Status;
import com.ospedale.controller.NotificationController;

/**
 *
 * @author jjlora
 * @author edangulo
 * @author marianaserrato
 * @author orarroyo
 */
public class PatientDashboardView extends javax.swing.JFrame {

    private int x, y;
    private User user;
    private ArrayList<User> users;
    private Patient patient;
    private ArrayList<Appointment> appointments;
    private ArrayList<Hospitalization> hospitalizations;

    public PatientDashboardView(User user,Patient patient, ArrayList<User> users, ArrayList<Appointment>appointments, ArrayList<Hospitalization> hospitalizations) {
        initComponents();
        this.user = user;
        this.users = users;
        this.patient = patient;
        this.hospitalizations = hospitalizations;
        this.appointments = appointments;
        if (user instanceof Administrator) {
            BackButton.setVisible(true);
        } else {
            BackButton.setVisible(false);
        }
        this.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GeneralPane = new com.ospedale.view.PanelRound();
        TitleBar = new com.ospedale.view.PanelRound();
        CloseBtn = new javax.swing.JButton();
        TitleLabel = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        TabbedPane = new javax.swing.JTabbedPane();
        AppointmentHistoryPane = new javax.swing.JPanel();
        AppointmentViewScrlPane = new javax.swing.JScrollPane();
        AppointmentViewTable = new javax.swing.JTable();
        RefreshBtn = new javax.swing.JButton();
        LogoutBtn = new javax.swing.JButton();
        ModifyInfoPane = new javax.swing.JPanel();
        FirstNameLabel = new javax.swing.JLabel();
        FirstNameTxt = new javax.swing.JTextField();
        LastNameLabel = new javax.swing.JLabel();
        LastNameTxt = new javax.swing.JTextField();
        BirthdateLabel = new javax.swing.JLabel();
        BirthdateTxt = new javax.swing.JTextField();
        GenderLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        EmailTxt = new javax.swing.JTextField();
        PhoneLabel = new javax.swing.JLabel();
        PhoneTxt = new javax.swing.JTextField();
        AddressLabel = new javax.swing.JLabel();
        AddressTxt = new javax.swing.JTextField();
        PasswdTxt = new javax.swing.JTextField();
        PasswdLabel = new javax.swing.JLabel();
        PasswdConfLabel = new javax.swing.JLabel();
        PasswdConfTxt = new javax.swing.JTextField();
        SaveBtn = new javax.swing.JButton();
        UserNameLabel = new javax.swing.JLabel();
        UserNameTxt = new javax.swing.JTextField();
        GenderDropdown = new javax.swing.JComboBox<>();
        Request_CancelAppointmentPane = new javax.swing.JPanel();
        RequestAppointmentPaneLabel = new javax.swing.JLabel();
        SpecialtySelBtn = new javax.swing.JRadioButton();
        DoctorSelBtn = new javax.swing.JRadioButton();
        ReqsSeparator = new javax.swing.JSeparator();
        AppointmentDateLabel = new javax.swing.JLabel();
        AppointmentDateTxt = new javax.swing.JTextField();
        AppointmentTimeTxt = new javax.swing.JTextField();
        AppointmentTimeLabel = new javax.swing.JLabel();
        AppointmentTypeLabel = new javax.swing.JLabel();
        AppointmentReasonLabel = new javax.swing.JLabel();
        AppointmentTypeDropdown = new javax.swing.JComboBox<>();
        CreateAppointmentBtn = new javax.swing.JButton();
        ReqHosp_CancelSeparator = new javax.swing.JSeparator();
        RequestHospitalizationPaneLabel = new javax.swing.JLabel();
        HospReasonLabel = new javax.swing.JLabel();
        HospDoctorLabel = new javax.swing.JLabel();
        HospDoctorDropdown = new javax.swing.JComboBox<>();
        AdmissionDateTxt = new javax.swing.JTextField();
        AdmissionDateLabel = new javax.swing.JLabel();
        DesiredRoomLabel = new javax.swing.JLabel();
        DesiredRoomDropdown = new javax.swing.JComboBox<>();
        HospObservationsLabel = new javax.swing.JLabel();
        HospObservationsScrlPane = new javax.swing.JScrollPane();
        HospObservationsTxt = new javax.swing.JTextArea();
        CreateHospReqBtn = new javax.swing.JButton();
        CancelAppointmentPaneLabel = new javax.swing.JLabel();
        AppointmentIDLabel = new javax.swing.JLabel();
        AppointmentObservationsLabel = new javax.swing.JLabel();
        AppointmentObservationsScrlPane = new javax.swing.JScrollPane();
        AppointmentObservationsTxt = new javax.swing.JTextArea();
        CancelAppointmentBtn = new javax.swing.JButton();
        ReqHospReasonScrlPane = new javax.swing.JScrollPane();
        ReqHospReasonTxt = new javax.swing.JTextArea();
        AppointmentReasonScrlPane = new javax.swing.JScrollPane();
        AppointmentReasonTxt = new javax.swing.JTextArea();
        AppointmentIDDropdown = new javax.swing.JComboBox<>();
        DoctorSelDropdown = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        GeneralPane.setRadius(50);

        TitleBar.setRadius(50);
        TitleBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                TitleBarMouseDragged(evt);
            }
        });
        TitleBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TitleBarMousePressed(evt);
            }
        });

        CloseBtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        CloseBtn.setText("X");
        CloseBtn.setBorderPainted(false);
        CloseBtn.setContentAreaFilled(false);
        CloseBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CloseBtn.setFocusable(false);
        CloseBtn.setRequestFocusEnabled(false);
        CloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseBtnActionPerformed(evt);
            }
        });

        TitleLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        TitleLabel.setText("PATIENT VIEW");

        BackButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TitleBarLayout = new javax.swing.GroupLayout(TitleBar);
        TitleBar.setLayout(TitleBarLayout);
        TitleBarLayout.setHorizontalGroup(
            TitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TitleBarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(TitleLabel)
                .addGap(29, 29, 29)
                .addComponent(BackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CloseBtn)
                .addGap(19, 19, 19))
        );
        TitleBarLayout.setVerticalGroup(
            TitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TitleBarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(CloseBtn))
            .addGroup(TitleBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(TitleLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        AppointmentViewTable.setAutoCreateRowSorter(true);
        AppointmentViewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Date", "Doctor", "Specialty", "Type", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        AppointmentViewScrlPane.setViewportView(AppointmentViewTable);

        RefreshBtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        RefreshBtn.setText("Refresh");
        RefreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshBtnActionPerformed(evt);
            }
        });

        LogoutBtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        LogoutBtn.setText("Logout");
        LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AppointmentHistoryPaneLayout = new javax.swing.GroupLayout(AppointmentHistoryPane);
        AppointmentHistoryPane.setLayout(AppointmentHistoryPaneLayout);
        AppointmentHistoryPaneLayout.setHorizontalGroup(
            AppointmentHistoryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AppointmentHistoryPaneLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(AppointmentViewScrlPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(AppointmentHistoryPaneLayout.createSequentialGroup()
                .addGap(602, 602, 602)
                .addComponent(RefreshBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoutBtn)
                .addGap(78, 78, 78))
        );
        AppointmentHistoryPaneLayout.setVerticalGroup(
            AppointmentHistoryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AppointmentHistoryPaneLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(AppointmentViewScrlPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(AppointmentHistoryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RefreshBtn)
                    .addComponent(LogoutBtn))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Appointment history", AppointmentHistoryPane);

        FirstNameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        FirstNameLabel.setText("Firstname");

        FirstNameTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        LastNameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        LastNameLabel.setText("Lastname");

        LastNameTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        BirthdateLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        BirthdateLabel.setText("Birthdate");

        BirthdateTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        GenderLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        GenderLabel.setText("Gender");

        EmailLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        EmailLabel.setText("Email");

        EmailTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        PhoneLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PhoneLabel.setText("Phone");

        PhoneTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        AddressLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AddressLabel.setText("Address");

        AddressTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        PasswdTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        PasswdLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PasswdLabel.setText("Password");

        PasswdConfLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PasswdConfLabel.setText("Password confirmation");

        PasswdConfTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        SaveBtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        SaveBtn.setText("Save");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        UserNameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        UserNameLabel.setText("User");

        UserNameTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        GenderDropdown.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        GenderDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Female", "Male" }));

        javax.swing.GroupLayout ModifyInfoPaneLayout = new javax.swing.GroupLayout(ModifyInfoPane);
        ModifyInfoPane.setLayout(ModifyInfoPaneLayout);
        ModifyInfoPaneLayout.setHorizontalGroup(
            ModifyInfoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModifyInfoPaneLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(FirstNameLabel)
                .addGap(18, 18, 18)
                .addComponent(FirstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(LastNameLabel)
                .addGap(18, 18, 18)
                .addGroup(ModifyInfoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModifyInfoPaneLayout.createSequentialGroup()
                        .addComponent(PhoneLabel)
                        .addGap(18, 18, 18)
                        .addComponent(PhoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AddressLabel)
                        .addGap(18, 18, 18)
                        .addComponent(AddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ModifyInfoPaneLayout.createSequentialGroup()
                        .addComponent(LastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BirthdateLabel)
                        .addGap(18, 18, 18)
                        .addComponent(BirthdateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(GenderLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GenderDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(EmailLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(EmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(141, 141, 141))
            .addGroup(ModifyInfoPaneLayout.createSequentialGroup()
                .addGap(516, 516, 516)
                .addGroup(ModifyInfoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModifyInfoPaneLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(SaveBtn))
                    .addGroup(ModifyInfoPaneLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(PasswdConfTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PasswdConfLabel)
                    .addGroup(ModifyInfoPaneLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(PasswdLabel))
                    .addGroup(ModifyInfoPaneLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(ModifyInfoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ModifyInfoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(UserNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(ModifyInfoPaneLayout.createSequentialGroup()
                                    .addGap(39, 39, 39)
                                    .addComponent(UserNameLabel)))
                            .addComponent(PasswdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ModifyInfoPaneLayout.setVerticalGroup(
            ModifyInfoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModifyInfoPaneLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(ModifyInfoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameLabel)
                    .addComponent(FirstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastNameLabel)
                    .addComponent(LastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BirthdateLabel)
                    .addComponent(BirthdateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GenderLabel)
                    .addComponent(EmailLabel)
                    .addComponent(EmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GenderDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ModifyInfoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneLabel)
                    .addComponent(PhoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddressLabel)
                    .addComponent(AddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(UserNameLabel)
                .addGap(18, 18, 18)
                .addComponent(UserNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PasswdLabel)
                .addGap(18, 18, 18)
                .addComponent(PasswdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PasswdConfLabel)
                .addGap(18, 18, 18)
                .addComponent(PasswdConfTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(SaveBtn)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Modify info", ModifyInfoPane);

        RequestAppointmentPaneLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        RequestAppointmentPaneLabel.setText("Request medical appointment");

        SpecialtySelBtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        SpecialtySelBtn.setText("Specialty");
        SpecialtySelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpecialtySelBtnActionPerformed(evt);
            }
        });

        DoctorSelBtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        DoctorSelBtn.setText("Doctor");
        DoctorSelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorSelBtnActionPerformed(evt);
            }
        });

        ReqsSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        AppointmentDateLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AppointmentDateLabel.setText("Appointment date");

        AppointmentDateTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        AppointmentTimeTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        AppointmentTimeLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AppointmentTimeLabel.setText("Appointment time");

        AppointmentTypeLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AppointmentTypeLabel.setText("Appointment type");

        AppointmentReasonLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AppointmentReasonLabel.setText("Appointment reason");

        AppointmentTypeDropdown.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AppointmentTypeDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Remote", "In-person" }));

        CreateAppointmentBtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        CreateAppointmentBtn.setText("Create");
        CreateAppointmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateAppointmentBtnActionPerformed(evt);
            }
        });

        ReqHosp_CancelSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        RequestHospitalizationPaneLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        RequestHospitalizationPaneLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RequestHospitalizationPaneLabel.setText("Request hospitalization");

        HospReasonLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        HospReasonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HospReasonLabel.setText("Hospitalization reason");

        HospDoctorLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        HospDoctorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HospDoctorLabel.setText("Attending doctor");

        HospDoctorDropdown.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        HospDoctorDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        AdmissionDateTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        AdmissionDateLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AdmissionDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdmissionDateLabel.setText("Estimated date of admission");
        AdmissionDateLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        DesiredRoomLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        DesiredRoomLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DesiredRoomLabel.setText("Desired room type");

        DesiredRoomDropdown.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        DesiredRoomDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        HospObservationsLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        HospObservationsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HospObservationsLabel.setText("Observations");

        HospObservationsTxt.setColumns(20);
        HospObservationsTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        HospObservationsTxt.setRows(5);
        HospObservationsScrlPane.setViewportView(HospObservationsTxt);

        CreateHospReqBtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        CreateHospReqBtn.setText("Create");
        CreateHospReqBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateHospReqBtnActionPerformed(evt);
            }
        });

        CancelAppointmentPaneLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        CancelAppointmentPaneLabel.setText("Cancel appointment");

        AppointmentIDLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AppointmentIDLabel.setText("ID appointment");

        AppointmentObservationsLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AppointmentObservationsLabel.setText("Observations");

        AppointmentObservationsTxt.setColumns(20);
        AppointmentObservationsTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AppointmentObservationsTxt.setRows(5);
        AppointmentObservationsScrlPane.setViewportView(AppointmentObservationsTxt);

        CancelAppointmentBtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        CancelAppointmentBtn.setText("Cancel");
        CancelAppointmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelAppointmentBtnActionPerformed(evt);
            }
        });

        ReqHospReasonTxt.setColumns(20);
        ReqHospReasonTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        ReqHospReasonTxt.setRows(5);
        ReqHospReasonScrlPane.setViewportView(ReqHospReasonTxt);

        AppointmentReasonTxt.setColumns(20);
        AppointmentReasonTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AppointmentReasonTxt.setRows(5);
        AppointmentReasonScrlPane.setViewportView(AppointmentReasonTxt);

        AppointmentIDDropdown.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AppointmentIDDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        DoctorSelDropdown.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        DoctorSelDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        javax.swing.GroupLayout Request_CancelAppointmentPaneLayout = new javax.swing.GroupLayout(Request_CancelAppointmentPane);
        Request_CancelAppointmentPane.setLayout(Request_CancelAppointmentPaneLayout);
        Request_CancelAppointmentPaneLayout.setHorizontalGroup(
            Request_CancelAppointmentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Request_CancelAppointmentPaneLayout.createSequentialGroup()
                .addGroup(Request_CancelAppointmentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Request_CancelAppointmentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(Request_CancelAppointmentPaneLayout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addGroup(Request_CancelAppointmentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(Request_CancelAppointmentPaneLayout.createSequentialGroup()
                                    .addComponent(SpecialtySelBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DoctorSelBtn))
                                .addGroup(Request_CancelAppointmentPaneLayout.createSequentialGroup()
                                    .addGap(63, 63, 63)
                                    .addComponent(AppointmentDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(Request_CancelAppointmentPaneLayout.createSequentialGroup()
                                    .addGap(47, 47, 47)
                                    .addGroup(Request_CancelAppointmentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(AppointmentTimeLabel)
                                        .addComponent(AppointmentDateLabel)
                                        .addComponent(DoctorSelDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(Request_CancelAppointmentPaneLayout.createSequentialGroup()
                                    .addGap(63, 63, 63)
                                    .addComponent(AppointmentTimeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(Request_CancelAppointmentPaneLayout.createSequentialGroup()
                                    .addGap(38, 38, 38)
                                    .addComponent(AppointmentReasonLabel))
                                .addGroup(Request_CancelAppointmentPaneLayout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addComponent(AppointmentTypeLabel))
                                .addGroup(Request_CancelAppointmentPaneLayout.createSequentialGroup()
                                    .addGap(55, 55, 55)
                                    .addComponent(AppointmentTypeDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(Request_CancelAppointmentPaneLayout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addComponent(RequestAppointmentPaneLabel)))
                    .addGroup(Request_CancelAppointmentPaneLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(AppointmentReasonScrlPane, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Request_CancelAppointmentPaneLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(CreateAppointmentBtn)))
                .addGap(69, 69, 69)
                .addComponent(ReqsSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(Request_CancelAppointmentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Request_CancelAppointmentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Request_CancelAppointmentPaneLayout.createSequentialGroup()
                            .addGap(211, 211, 211)
                            .addComponent(CreateHospReqBtn))
                        .addGroup(Request_CancelAppointmentPaneLayout.createSequentialGroup()
                            .addGap(127, 127, 127)
                            .addGroup(Request_CancelAppointmentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(HospReasonLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ReqHospReasonScrlPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(RequestHospitalizationPaneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                .addComponent(HospDoctorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Request_CancelAppointmentPaneLayout.createSequentialGroup()
                            .addGap(127, 127, 127)
                            .addGroup(Request_CancelAppointmentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(HospObservationsLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AdmissionDateLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(HospObservationsScrlPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DesiredRoomLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(Request_CancelAppointmentPaneLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(HospDoctorDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Request_CancelAppointmentPaneLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(AdmissionDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Request_CancelAppointmentPaneLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(DesiredRoomDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(ReqHosp_CancelSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(Request_CancelAppointmentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AppointmentObservationsScrlPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Request_CancelAppointmentPaneLayout.createSequentialGroup()
                        .addGroup(Request_CancelAppointmentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Request_CancelAppointmentPaneLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(CancelAppointmentPaneLabel))
                            .addGroup(Request_CancelAppointmentPaneLayout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(CancelAppointmentBtn))
                            .addGroup(Request_CancelAppointmentPaneLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(Request_CancelAppointmentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(AppointmentIDDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AppointmentIDLabel)))
                            .addGroup(Request_CancelAppointmentPaneLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(AppointmentObservationsLabel)))
                        .addGap(49, 49, 49)))
                .addGap(81, 81, 81))
        );
        Request_CancelAppointmentPaneLayout.setVerticalGroup(
            Request_CancelAppointmentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ReqsSeparator)
            .addComponent(ReqHosp_CancelSeparator)
            .addGroup(Request_CancelAppointmentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Request_CancelAppointmentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Request_CancelAppointmentPaneLayout.createSequentialGroup()
                        .addComponent(RequestHospitalizationPaneLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(HospReasonLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ReqHospReasonScrlPane, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(HospDoctorLabel)
                        .addGap(18, 18, 18)
                        .addComponent(HospDoctorDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AdmissionDateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AdmissionDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(DesiredRoomLabel)
                        .addGap(18, 18, 18)
                        .addComponent(DesiredRoomDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(HospObservationsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(HospObservationsScrlPane, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CreateHospReqBtn)
                        .addGap(15, 15, 15))
                    .addGroup(Request_CancelAppointmentPaneLayout.createSequentialGroup()
                        .addGroup(Request_CancelAppointmentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Request_CancelAppointmentPaneLayout.createSequentialGroup()
                                .addComponent(RequestAppointmentPaneLabel)
                                .addGap(18, 18, 18)
                                .addGroup(Request_CancelAppointmentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(SpecialtySelBtn)
                                    .addComponent(DoctorSelBtn))
                                .addGap(18, 18, 18)
                                .addComponent(DoctorSelDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AppointmentDateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AppointmentDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(AppointmentTimeLabel)
                                .addGap(18, 18, 18)
                                .addComponent(AppointmentTimeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AppointmentReasonLabel)
                                .addGap(24, 24, 24)
                                .addComponent(AppointmentReasonScrlPane, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Request_CancelAppointmentPaneLayout.createSequentialGroup()
                                .addComponent(CancelAppointmentPaneLabel)
                                .addGap(39, 39, 39)
                                .addComponent(AppointmentIDLabel)
                                .addGap(18, 18, 18)
                                .addComponent(AppointmentIDDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(AppointmentObservationsLabel)
                                .addGap(18, 18, 18)
                                .addComponent(AppointmentObservationsScrlPane, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(CancelAppointmentBtn)))
                        .addGap(18, 18, 18)
                        .addComponent(AppointmentTypeLabel)
                        .addGap(18, 18, 18)
                        .addComponent(AppointmentTypeDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(CreateAppointmentBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        TabbedPane.addTab("Request/Cancel", Request_CancelAppointmentPane);

        javax.swing.GroupLayout GeneralPaneLayout = new javax.swing.GroupLayout(GeneralPane);
        GeneralPane.setLayout(GeneralPaneLayout);
        GeneralPaneLayout.setHorizontalGroup(
            GeneralPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TitleBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TabbedPane)
        );
        GeneralPaneLayout.setVerticalGroup(
            GeneralPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeneralPaneLayout.createSequentialGroup()
                .addComponent(TitleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TabbedPane))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GeneralPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GeneralPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TitleBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TitleBarMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_TitleBarMousePressed

    private void TitleBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TitleBarMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_TitleBarMouseDragged

    private void CloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_CloseBtnActionPerformed

    private void CancelAppointmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelAppointmentBtnActionPerformed
        String idAppointment = AppointmentIDDropdown.getItemAt(AppointmentIDDropdown.getSelectedIndex());
        Response response = AppointmentController.cancelAppointment(idAppointment, String.valueOf(patient.getId()));
        if (response.getStatus() == Status.OK) {
            NotificationController.notifySuccess(response.getMessage(), this);
        } else {
            NotificationController.notifyError(response.getMessage(), this);
        }
    }//GEN-LAST:event_CancelAppointmentBtnActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        String firstname = FirstNameTxt.getText();
        String lastname = LastNameTxt.getText();
        boolean gender = (GenderDropdown.getSelectedIndex() == 0 ? null : (GenderDropdown.getSelectedIndex() == 1));
        String birth = BirthdateTxt.getText();
        String address = AddressTxt.getText();
        String phoneStr = PhoneTxt.getText();
        String email = EmailTxt.getText();
        String username = UserNameTxt.getText();
        String password = PasswdTxt.getText();
        String comPassword = PasswdConfTxt.getText();
        
        Response response = PatientController.updatePatient(String.valueOf(this.user.getId()), username, firstname, lastname, password, comPassword, email, birth, gender, phoneStr, address);
        if (response.getStatus() == Status.OK) {
            NotificationController.notifySuccess(response.getMessage(), this);
        } else {
            NotificationController.notifyError(response.getMessage(), this);
        }
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtnActionPerformed
        LoginRegistrationView login = new LoginRegistrationView();
        this.setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_LogoutBtnActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        AdminDashboardView admin = new AdminDashboardView(user);
        this.setVisible(false);
        admin.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void SpecialtySelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpecialtySelBtnActionPerformed
        if (DoctorSelBtn.isSelected()) {
            DoctorSelBtn.setSelected(false);
        }

        DoctorSelDropdown.removeAllItems();

        DoctorSelDropdown.addItem("Select one");
        for (Specialty spec : Specialty.values()) {
            DoctorSelDropdown.addItem(spec.toString().replaceAll("_", " & "));
        }
    }//GEN-LAST:event_SpecialtySelBtnActionPerformed

    private void DoctorSelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorSelBtnActionPerformed
        if (SpecialtySelBtn.isSelected()) {
            SpecialtySelBtn.setSelected(false);
        }
        DoctorSelDropdown.removeAllItems();

        DoctorSelDropdown.addItem("Select one");
        for (User doc : this.users) {
            if (doc instanceof Doctor) {
                DoctorSelDropdown.addItem(doc.getFirstname() + " " + doc.getLastname());
            }
        }
    }//GEN-LAST:event_DoctorSelBtnActionPerformed

    private void CreateAppointmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAppointmentBtnActionPerformed
        String appointDate = AppointmentDateTxt.getText();
        String appointmentTime = AppointmentTimeTxt.getText();
        String appointmentReason = AppointmentReasonTxt.getText();
        
        String doctorIdStr = null;
        if (DoctorSelDropdown.getSelectedIndex() > 0) {
            String doctorName = DoctorSelDropdown.getItemAt(DoctorSelDropdown.getSelectedIndex());
            for (User u : this.users) {
                if (u instanceof Doctor && (u.getFirstname() + " " + u.getLastname()).equals(doctorName)) {
                    doctorIdStr = String.valueOf(u.getId());
                    break;
                }
            }
        }
        
        String specialtyStr = null;
        if (doctorIdStr == null && DoctorSelDropdown.getSelectedIndex() > 0) {
             specialtyStr = DoctorSelDropdown.getItemAt(DoctorSelDropdown.getSelectedIndex()).replaceAll(" & ", "_");
        }

        boolean isRemote = (AppointmentTypeDropdown.getSelectedIndex() != 2);
        
        Response response = AppointmentController.createAppointment(String.valueOf(patient.getId()), appointDate, appointmentTime, doctorIdStr, specialtyStr, appointmentReason, isRemote);
        if (response.getStatus() == Status.CREATED) {
            NotificationController.notifySuccess(response.getMessage(), this);
        } else {
            NotificationController.notifyError(response.getMessage(), this);
        }
    }//GEN-LAST:event_CreateAppointmentBtnActionPerformed


    private void RefreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshBtnActionPerformed
        Patient p = (Patient) user;
        DefaultTableModel model = (DefaultTableModel) AppointmentViewTable.getModel();
        model.setRowCount(0);
        for (Appointment a : p.getAppointments()) {
            model.addRow(new Object[]{a.getId(), a.getDatetime().toString(), a.getDoctor().getFirstname() + " " + a.getDoctor().getLastname(), a.getSpecialty().name(), a.isType() ? "In-person" : "Remote", a.getStatus().name()});
        }
    }//GEN-LAST:event_RefreshBtnActionPerformed

    private void CreateHospReqBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateHospReqBtnActionPerformed
        String hospitalizationReason = ReqHospReasonTxt.getText();
        String roomTypeStr = DesiredRoomDropdown.getItemAt(DesiredRoomDropdown.getSelectedIndex()).toUpperCase();
        String estDate = AdmissionDateTxt.getText();
        
        Response response = HospitalizationController.createHospitalization(String.valueOf(patient.getId()), estDate, hospitalizationReason, roomTypeStr);
        if (response.getStatus() == Status.CREATED || response.getStatus() == Status.OK) {
            NotificationController.notifySuccess(response.getMessage(), this);
        } else {
            NotificationController.notifyError(response.getMessage(), this);
        }
    }//GEN-LAST:event_CreateHospReqBtnActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JTextField AddressTxt;
    private javax.swing.JLabel AdmissionDateLabel;
    private javax.swing.JTextField AdmissionDateTxt;
    private javax.swing.JLabel AppointmentDateLabel;
    private javax.swing.JTextField AppointmentDateTxt;
    private javax.swing.JPanel AppointmentHistoryPane;
    private javax.swing.JComboBox<String> AppointmentIDDropdown;
    private javax.swing.JLabel AppointmentIDLabel;
    private javax.swing.JLabel AppointmentObservationsLabel;
    private javax.swing.JScrollPane AppointmentObservationsScrlPane;
    private javax.swing.JTextArea AppointmentObservationsTxt;
    private javax.swing.JLabel AppointmentReasonLabel;
    private javax.swing.JScrollPane AppointmentReasonScrlPane;
    private javax.swing.JTextArea AppointmentReasonTxt;
    private javax.swing.JLabel AppointmentTimeLabel;
    private javax.swing.JTextField AppointmentTimeTxt;
    private javax.swing.JComboBox<String> AppointmentTypeDropdown;
    private javax.swing.JLabel AppointmentTypeLabel;
    private javax.swing.JScrollPane AppointmentViewScrlPane;
    private javax.swing.JTable AppointmentViewTable;
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel BirthdateLabel;
    private javax.swing.JTextField BirthdateTxt;
    private javax.swing.JButton CancelAppointmentBtn;
    private javax.swing.JLabel CancelAppointmentPaneLabel;
    private javax.swing.JButton CloseBtn;
    private javax.swing.JButton CreateAppointmentBtn;
    private javax.swing.JButton CreateHospReqBtn;
    private javax.swing.JComboBox<String> DesiredRoomDropdown;
    private javax.swing.JLabel DesiredRoomLabel;
    private javax.swing.JRadioButton DoctorSelBtn;
    private javax.swing.JComboBox<String> DoctorSelDropdown;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JTextField EmailTxt;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JTextField FirstNameTxt;
    private javax.swing.JComboBox<String> GenderDropdown;
    private javax.swing.JLabel GenderLabel;
    private com.ospedale.view.PanelRound GeneralPane;
    private javax.swing.JComboBox<String> HospDoctorDropdown;
    private javax.swing.JLabel HospDoctorLabel;
    private javax.swing.JLabel HospObservationsLabel;
    private javax.swing.JScrollPane HospObservationsScrlPane;
    private javax.swing.JTextArea HospObservationsTxt;
    private javax.swing.JLabel HospReasonLabel;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JTextField LastNameTxt;
    private javax.swing.JButton LogoutBtn;
    private javax.swing.JPanel ModifyInfoPane;
    private javax.swing.JLabel PasswdConfLabel;
    private javax.swing.JTextField PasswdConfTxt;
    private javax.swing.JLabel PasswdLabel;
    private javax.swing.JTextField PasswdTxt;
    private javax.swing.JLabel PhoneLabel;
    private javax.swing.JTextField PhoneTxt;
    private javax.swing.JButton RefreshBtn;
    private javax.swing.JScrollPane ReqHospReasonScrlPane;
    private javax.swing.JTextArea ReqHospReasonTxt;
    private javax.swing.JSeparator ReqHosp_CancelSeparator;
    private javax.swing.JSeparator ReqsSeparator;
    private javax.swing.JLabel RequestAppointmentPaneLabel;
    private javax.swing.JLabel RequestHospitalizationPaneLabel;
    private javax.swing.JPanel Request_CancelAppointmentPane;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JRadioButton SpecialtySelBtn;
    private javax.swing.JTabbedPane TabbedPane;
    private com.ospedale.view.PanelRound TitleBar;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JLabel UserNameLabel;
    private javax.swing.JTextField UserNameTxt;
    // End of variables declaration//GEN-END:variables
}
